import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,dirname,extname} from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
if(process.argv.length!==3)throw new Error('Usage: node artifacts/signals/browser-qa.mjs <new-output-directory>');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),out=resolve(process.argv[2]);await mkdir(out);
const server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;path=path==='/signals/'?'web/signals.html':path.slice(1);if(!/^(web|src)\/[a-zA-Z0-9_./-]+\.(html|js|css)$/.test(path)||path.includes('..'))throw new Error('missing');res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[extname(path)]);res.end(await readFile(resolve(root,path)));}catch{res.statusCode=404;res.end('missing');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/signals/`,browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
try{
 for(const width of [320,390,1280]){
  const context=await browser.newContext({viewport:{width,height:844},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.goto(url);await page.locator('#action-canal').waitFor();
  const first=await page.locator('#action-canal').boundingBox(),overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);assert.ok(first.y+first.height<844);await page.screenshot({path:resolve(out,`${width}-initial.png`),fullPage:true});
  const event=()=>page.locator('#next-event').click();const action=name=>page.locator(`#action-${name}`).click();const fresh=async(situation='turning')=>{await page.locator('#new-episode').evaluate(e=>e.open=true);await page.locator('#situation').selectOption(situation);await page.locator('#restart').click();};
  await action('radio');await event();assert.equal(await page.locator('#minute').textContent(),'01');await action('lookout');await event();assert.equal(await page.locator('#report-value').textContent(),'open');await event();assert.equal(await page.locator('#minute').textContent(),'06');assert.equal(await page.locator('#report-value').textContent(),'open');await page.locator('#receipt-details').evaluate(e=>e.open=true);assert.match(await page.locator('#receipts').textContent(),/older than your notebook/);
  const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;const saved=resolve(out,`${width}-save.json`);await download.saveAs(saved);const before=await page.evaluate(()=>localStorage.getItem('human-last-light-v1'));
  await page.locator('#load').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"wrong"}')});await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('not loaded'));assert.equal(await page.evaluate(()=>localStorage.getItem('human-last-light-v1')),before);await page.locator('#load').setInputFiles(saved);await page.waitForFunction(()=>document.getElementById('notice').hidden);assert.equal(await page.locator('#minute').textContent(),'06');
  await fresh();await action('radio');await event();await action('lookout');await event();await action('canal');await event();assert.equal(await page.locator('#minute').textContent(),'06');assert.match(await page.locator('#job').textContent(),/canal/);await event();assert.match(await page.locator('#outcome-title').textContent(),/launch sails/);assert.equal(await page.locator('#minute').textContent(),'10');await page.screenshot({path:resolve(out,`${width}-launch.png`),fullPage:true});
  await fresh();await action('ridge');await event();assert.equal(await page.locator('#minute').textContent(),'12');await event();assert.equal(await page.locator('#minute').textContent(),'14');assert.match(await page.locator('#outcome-title').textContent(),/overnight/);
  await fresh('shut');await action('canal');await event();assert.equal(await page.locator('#minute').textContent(),'06');assert.match(await page.locator('#journal').textContent(),/At the canal lock/);await action('ridge');await event();await event();assert.equal(await page.locator('#minute').textContent(),'20');assert.match(await page.locator('#outcome-detail').textContent(),/closed crossing/);
  await fresh();await event();await event();assert.match(await page.locator('#outcome-title').textContent(),/closed before/);assert.equal(await page.locator('#minute').textContent(),'32');
  await fresh();await action('radio');await page.locator('#play').click();await page.waitForFunction(()=>document.getElementById('minute').textContent==='01');assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');await page.reload();assert.equal(await page.locator('#minute').textContent(),'01');assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');await page.waitForTimeout(1100);assert.equal(await page.locator('#minute').textContent(),'01');
  assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);results.push({width,height:844,firstActionBottom:first.y+first.height,noOverflow:true,paidRadioAndStaleReceipt:true,downloadImport:true,invalidImportPreserved:true,launchAndOvernightRoutes:true,failedCrossingPivot:true,finiteFailure:true,pausedReload:true,pageErrors:errors});await context.close();
 }
 await writeFile(resolve(out,'browser.json'),JSON.stringify({browser:browser.version(),scope:'Desktop Chrome at mobile viewport widths; local isolated Signals route. No physical-device or public-deployment claim.',results},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({out,browser:browser.version(),results},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));}
