import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {createAppServer} from './source/scripts/serve.js';
import {writeFile} from 'node:fs/promises';
const root='/tmp/hf-game-hud-review-20260908',server=createAppServer({root:root+'/source'});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const ctx=await browser.newContext({viewport:{width:375,height:667},acceptDownloads:true});let page;
async function start(game){if(page)await page.close();page=await ctx.newPage();page.on('pageerror',e=>results.push({error:e.message}));await page.goto(origin+'/'+game+'/');await page.waitForTimeout(50);}
async function clickTab(n){await page.locator('#game-tab-'+n).click();}
async function shot(name){await page.screenshot({path:root+'/'+name+'.png',fullPage:true});return await page.evaluate(()=>({selected:document.querySelector('[role=tab][aria-selected=true]')?.textContent,focus:document.activeElement.id,panelText:document.querySelector('[role=tabpanel]:not([hidden])')?.innerText,clock:document.querySelector('.hud-clock')?.innerText,work:document.querySelector('.game-dock')?.innerText,play:document.getElementById('play')?.getAttribute('aria-pressed'),panelHeight:document.querySelector('.game-content')?.clientHeight,docHeight:document.documentElement.scrollHeight}));}
try{
 await start('courtyard');for(let i=0;i<18;i++)await page.locator('[data-action=rest]').click();results.push({case:'courtyard-ended',...await shot('courtyard-ended')});await page.locator('#again').click();results.push({case:'courtyard-again',...await shot('courtyard-again')});
 await start('signals');await clickTab(1);await page.locator('#action-radio').click();await page.locator('#next-event').click();await page.locator('#action-lookout').click();await clickTab(0);await page.locator('#next-event').click();results.push({case:'signals-direct-report-while-route',...await shot('signals-report')});await page.locator('#next-event').click();results.push({case:'signals-stale-reply-while-route',...await shot('signals-stale')});
 await clickTab(4);const d=page.waitForEvent('download');await page.locator('#download').click();await (await d).saveAs(root+'/signals-save.json');const before=await page.evaluate(()=>localStorage.getItem('human-last-light-v1'));await page.locator('#load').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from('{"bad":true}')});await page.waitForTimeout(50);results.push({case:'signals-invalid-import-preserves',preserved:before===await page.evaluate(()=>localStorage.getItem('human-last-light-v1')),visible:await page.locator('#notice').isVisible()});await page.locator('#load').setInputFiles(root+'/signals-save.json');await page.waitForTimeout(50);results.push({case:'signals-valid-import',...await shot('signals-import')});await page.reload();results.push({case:'signals-paused-reload',...await shot('signals-reload')});
 await start('service-plan');await page.locator('#play').click();await clickTab(4);await page.locator('.episode-overview > summary').click();const readStart=await page.locator('#minute').textContent();await page.waitForTimeout(1400);results.push({case:'service-plan-read-overview-while-playing',minuteBefore:readStart,minuteAfter:await page.locator('#minute').textContent(),...await shot('plan-read-overview')});await page.locator('#play').click();await clickTab(2);await page.locator('#plan-options > summary').click();await page.locator('#propose').click();await clickTab(0);results.push({case:'plan-pending-hidden-panel',stopVisible:await page.locator('#cancel-discussion').isVisible(),...await shot('plan-pending')});await page.locator('#cancel-discussion').click();results.push({case:'plan-interrupt-discussion',stopVisible:await page.locator('#cancel-discussion').isVisible(),...await shot('plan-interrupted')});
 await start('commons-next');await page.locator('#next-event').click();results.push({case:'rain-ferry-checkpoint',...await shot('rain-ferry')});await page.locator('#continue').click();results.push({case:'rain-after-ferry',...await shot('rain-after-ferry')});await page.locator('#next-event').click();results.push({case:'rain-dusk',...await shot('rain-dusk')});await page.locator('#continue').click();results.push({case:'rain-result',...await shot('rain-result')});
 await start('shift');await clickTab(1);await page.locator('[data-job]').first().click();results.push({case:'shift-select-yard',...await shot('shift-yard-selected')});await page.locator('#actions button').first().click();await page.locator('#end-shift').click();results.push({case:'shift-end',...await shot('shift-ended')});
 await start('workshop');await page.locator('#actions button').first().click();await page.locator('#advance').click();await clickTab(4);const dw=page.waitForEvent('download');await page.locator('#save').click();await(await dw).saveAs(root+'/workshop-save.json');await page.locator('#import').setInputFiles(root+'/workshop-save.json');await page.waitForTimeout(50);results.push({case:'workshop-pending-import',...await shot('workshop-import')});await page.locator('#finish').click();results.push({case:'workshop-finish-from-save',...await shot('workshop-finish')});
}catch(e){results.push({fatal:e.stack});}finally{await writeFile(root+'/lifecycle-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close();await new Promise(r=>server.close(r));}
