import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import * as p from '/Users/abdul/code/human-framework/src/games/across-cut-player.js';
const root='/Users/abdul/code/human-framework',dir='/tmp/action-offer-ui-review',key='human-across-cut-player-v0.1.0',files=['web/across-player.js','web/across-view.js','src/games/across-cut-player.js'];
const out={cases:[],sources:{},errors:[]},hash=x=>createHash('sha256').update(x).digest('hex');
async function source(label){out.sources[label]={};for(const file of files){const bytes=await fs.readFile(root+'/'+file);await fs.writeFile(dir+'/contact-'+label+'__'+file.replaceAll('/','__'),bytes);out.sources[label][file]=hash(bytes);}}
const browser=await chromium.launch({channel:'chrome',headless:true});
try {await source('before');for(const [name,fatigue]of [['legal',.91],['impossible',.93]]){
 let game=p.createGame({bodies:{keeper:{fatigue,hunger:.15}},channelMode:'bounded',channelOverrides:{'receiver:2':6}});game=p.applyCommand(game,{type:'request',action:{task:'travel',to:'dock'}});while(p.getGameView(game).job)game=p.advanceToNextEvent(game);assert.equal(p.getGameView(game).local.peerPresent,true);
 const save=p.exportGame(game);await fs.writeFile(dir+'/contact-'+name+'-recipe.json',JSON.stringify(save,null,2));const context=await browser.newContext({viewport:{width:375,height:667}});await context.addInitScript(({key,raw})=>localStorage.setItem(key,raw),{key,raw:JSON.stringify(save)});const page=await context.newPage();page.on('pageerror',e=>out.errors.push(String(e)));await page.goto('http://127.0.0.1:4191/across/');await page.locator('#tab-notebook').click();await page.getByText('Share your first-hand observations',{exact:true}).click();assert.equal(await page.locator('#send-contact').innerText(),'Try telling Deniz · 1 min');assert.equal(await page.locator('#send-contact').isEnabled(),true);const before=await page.evaluate(key=>({storage:localStorage.getItem(key),body:document.body.textContent}),key);await page.locator('#send-contact').focus();await page.keyboard.press('Enter');const after=await page.evaluate(key=>({storage:localStorage.getItem(key),focus:document.activeElement.id,notice:document.querySelector('#notice').textContent}),key);
 if(name==='legal'){const v=p.getGameView(p.restoreGame(JSON.parse(after.storage)));assert.equal(v.now,6);assert.equal(v.job.task,'transmit');assert.equal(v.job.via,'contact');assert.equal(v.inventory.radio.available,4);assert.equal(after.focus,'next-event');await page.locator('#one-minute').click();const completed=p.getGameView(p.restoreGame(JSON.parse(await page.evaluate(key=>localStorage.getItem(key),key))));assert.equal(completed.now,7);assert.equal(completed.paid.transmit,1);assert.equal(completed.sent[0].via,'contact');assert.equal(completed.inventory.radio.available,4);}else{assert.equal(after.storage,before.storage);assert.equal(after.focus,'send-contact');assert.match(after.notice,/cannot sustain/);}
 await page.screenshot({path:dir+'/contact-'+name+'.png',fullPage:true});out.cases.push({name,before,after});
 } assert.equal(out.cases[0].before.body,out.cases[1].before.body);
}catch(e){out.fatal={message:e.message,stack:e.stack};}finally{await source('after');out.sourceStable=files.every(f=>out.sources.before[f]===out.sources.after[f]);await fs.writeFile(dir+'/contact-results.json',JSON.stringify(out,null,2));await browser.close();console.log(JSON.stringify({cases:out.cases.map(x=>x.name),sourceStable:out.sourceStable,errors:out.errors,fatal:out.fatal},null,2));}
