import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import * as player from '/Users/abdul/code/human-framework/src/games/across-cut-player.js';
import {exportState} from '/Users/abdul/code/human-framework/src/games/across-cut.js';
const root='/Users/abdul/code/human-framework',dir='/tmp/action-offer-ui-review',origin='http://127.0.0.1:4191',key='human-across-cut-player-v0.1.0';
const results={checks:[],findings:[],browserErrors:[],sources:{},screenshots:[],fixtures:[]};
const paths=['src/games/across-cut-player.js','src/games/across-cut.js','src/games/across-cut-receiver.js','src/runtime/index.js','src/runtime/clock.js','src/human/v0.1.1.js','src/core/model.js','web/across-player.js','web/across-view.js','web/across.html','web/across.css','web/game-shell.css'];
const sha=x=>createHash('sha256').update(x).digest('hex');
async function capture(label){const entries={};for(const path of paths){const bytes=await fs.readFile(root+'/'+path);const local=dir+'/'+label+'__'+path.replaceAll('/','__');await fs.writeFile(local,bytes);entries[path]={sha256:sha(bytes),file:local};if(path.startsWith('web/')||path==='src/games/across-cut-player.js'){const res=await fetch(origin+'/'+(path==='web/across.html'?'across/':path));const body=Buffer.from(await res.arrayBuffer());entries[path].servedSha256=sha(body);assert.equal(res.status,200);assert.equal(sha(body),sha(bytes));}}results.sources[label]=entries;}
const request=(g,action)=>player.applyCommand(g,{type:'request',action});
const opts=fatigue=>({bodies:{keeper:{fatigue,hunger:.15}},channelMode:'bounded',channelOverrides:{'receiver:2':6}});
const browser=await chromium.launch({channel:'chrome',headless:true});
async function pageFor(name,game,viewport={width:375,height:667}){const context=await browser.newContext({viewport});const recipe=player.exportGame(game);const fixture=dir+'/'+name+'-recipe.json';await fs.writeFile(fixture,JSON.stringify(recipe,null,2));results.fixtures.push(fixture);await context.addInitScript(({key,raw})=>{if(localStorage.getItem(key)===null)localStorage.setItem(key,raw);},{key,raw:JSON.stringify(recipe)});const page=await context.newPage();page.on('pageerror',e=>results.browserErrors.push({name,error:String(e)}));await page.goto(origin+'/across/');await page.locator('#work-choices button').first().waitFor({state:'attached'});return page;}
async function state(p){return p.evaluate(key=>({minute:document.querySelector('#minute').textContent,resources:document.querySelector('#resources').textContent,condition:document.querySelector('#condition').textContent,job:document.querySelector('#job-label').textContent,timing:document.querySelector('#job-timing').textContent,notice:document.querySelector('#notice').textContent,status:document.querySelector('#time-status').textContent,focus:{tag:document.activeElement?.tagName,id:document.activeElement?.id,choice:document.activeElement?.dataset.choice},selected:document.querySelector('[role=tab][aria-selected=true]').id,storage:localStorage.getItem(key),bodyText:document.body.textContent,dimensions:{width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight}}),key);}
const stored=s=>player.restoreGame(JSON.parse(s.storage));
async function screen(p,name){const path=dir+'/'+name+'.png';await p.screenshot({path,fullPage:true});results.screenshots.push(path);}
async function reportPanel(p){await p.locator('#tab-notebook').click();await p.getByText('Share your first-hand observations',{exact:true}).click();}
async function record(name,data){results.checks.push({name,...data});await fs.writeFile(dir+'/results.json',JSON.stringify(results,null,2));}
async function controlsReachable(p){const dimensions=await p.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight}));assert.equal(dimensions.width,dimensions.scrollWidth);const records=[];for(const id of ['next-event','one-minute','stop'])if(await p.locator('#'+id).isVisible()){await p.locator('#'+id).scrollIntoViewIfNeeded();const r=await p.locator('#'+id).boundingBox();assert(r.width>=40&&r.height>=40);assert(r.y>=0&&r.y+r.height<=dimensions.height+1);records.push({id,rect:r});}return {dimensions,controls:records};}
try{
 await capture('before');
 for(const [name,size]of [['phone',{width:375,height:667}],['desktop',{width:1280,height:900}],['short',{width:375,height:500}]]){
  const legal=await pageFor(name+'-legal',player.createGame(opts(.9751)),size),impossible=await pageFor(name+'-impossible',player.createGame(opts(.9991)),size);
  const a=await state(legal),b=await state(impossible);assert.equal(a.bodyText,b.bodyText);assert.equal(a.condition,b.condition);
  for(const p of [legal,impossible]){assert.equal(await p.locator('[data-choice=inspect]').isEnabled(),true);assert.match(await p.locator('[data-choice=inspect]').innerText(),/Try inspection\s+1 min/);assert.match(await p.locator('#offer-note').innerText(),/may be refused/);}
  await screen(legal,name+'-uncertain-initial');await legal.locator('[data-choice=inspect]').focus();await legal.keyboard.press('Enter');let started=await state(legal);assert.equal(started.minute,'0');assert.equal(started.job,'Inspecting the station');assert.equal(started.focus.id,'next-event');assert.equal(player.getGameView(stored(started)).paid.inspect,0);await legal.locator('#one-minute').click();let paid=await state(legal);assert.equal(paid.minute,'1');assert.equal(player.getGameView(stored(paid)).paid.inspect,1);await record(name+' legal uncertain inspection starts explicitly and pays once',{beforeCondition:a.condition,started,paid,layout:await controlsReachable(legal)});
  await impossible.locator('[data-choice=inspect]').focus();await impossible.keyboard.press('Enter');const refused=await state(impossible);assert.equal(refused.storage,b.storage);assert.equal(refused.minute,'0');assert.equal(refused.resources,b.resources);assert.equal(refused.job,b.job);assert.match(refused.notice,/cannot sustain/);assert.equal(await impossible.locator('#notice').isVisible(),true);assert.deepEqual(exportState(stored(refused).host),exportState(stored(b).host));await screen(impossible,name+'-inspection-refused');await impossible.waitForTimeout(1000);assert.equal((await state(impossible)).storage,b.storage);
  if(refused.focus.tag==='BODY')results.findings.push({priority:'P2',name:'Work refusal removes the focused Try button',viewport:size,source:'web/across-player.js:15',repro:'Create synthetic keeper fatigue .9991/hunger .15; focus Try inspection; press Enter. The CAPACITY catch renders replacement choice buttons and focus becomes BODY.',observedFocus:refused.focus});
  await record(name+' impossible uncertain inspection refusal is atomic and does not retry',{before:b,after:refused,layout:await controlsReachable(impossible)});
 }
 // Legal and impossible radio requests use actual driver recipes and visible UI controls.
 for(const [name,fatigue]of [['legal',.9751],['impossible',.9991]]){
  const p=await pageFor('radio-'+name,player.createGame(opts(fatigue)));await reportPanel(p);const before=await state(p);assert.equal(await p.locator('#send-radio').innerText(),'Try sending by radio · 1 min');assert.equal(await p.locator('#send-radio').isEnabled(),true);assert.equal(await p.locator('#send-contact').isDisabled(),true);assert.match(await p.locator('#radio-note').innerText(),/may be refused without spending time or supplies/);await p.locator('#send-radio').focus();await p.keyboard.press('Enter');const after=await state(p);
  if(name==='legal'){assert.equal(after.job,'Sending a radio report');assert.equal(after.minute,'0');assert.equal(player.getGameView(stored(after)).inventory.radio.reserved,1);await p.locator('#one-minute').click();const done=player.getGameView(stored(await state(p)));assert.equal(done.paid.transmit,1);assert.equal(done.inventory.radio.consumed,1);assert.equal(done.sent.length,1);}else{assert.equal(after.storage,before.storage);assert.equal(after.focus.id,'send-radio');assert.match(after.notice,/cannot sustain/);await p.waitForTimeout(1000);assert.equal((await state(p)).storage,before.storage);}
  await screen(p,'radio-'+name);await record('radio '+name+' explicit try, one-minute cost, and keyboard focus',{before,after});
 }
 // Actual exhausted inventory and decision reserve are reconstructed from legal commands.
 let radioEmpty=player.createGame(opts(.9751));for(let i=0;i<4;i++)radioEmpty=player.advanceGame(request(radioEmpty,{task:'transmit',via:'radio',message:{kind:'report',observationIds:[1]}}),1);
 let budget=player.createGame(opts(.9751));for(let i=0;i<64;i++)budget=player.applyCommand(request(budget,{task:'inspect'}),{type:'stop'});
 let ended=player.createGame(opts(.9751));while(!player.getGameView(ended).ended)ended=player.advanceToNextEvent(ended);
 for(const [name,g]of [['radio-empty',radioEmpty],['busy',request(player.createGame(opts(.9751)),{task:'inspect'})],['budget',budget],['ended',ended]]){
  const p=await pageFor('blocked-'+name,g);await reportPanel(p);assert.equal(await p.locator('#send-radio').isDisabled(),true);assert.equal(await p.locator('#send-contact').isDisabled(),true);assert.doesNotMatch(await p.locator('#send-radio').innerText(),/^Try/);if(name!=='radio-empty'){await p.locator('#tab-work').click();assert.equal(await p.locator('[data-choice=inspect]').isDisabled(),true);assert.equal(await p.locator('#offer-note').isVisible(),false);}await screen(p,'blocked-'+name);await record(name+' structural blocker overrides uncertainty',{state:await state(p),radioNote:await p.locator('#radio-note').textContent()});
 }
 const selection=await pageFor('empty-selection',player.createGame(opts(.9751)));await reportPanel(selection);const inputs=selection.locator('#report-selection input');for(let i=0;i<await inputs.count();i++)await inputs.nth(i).uncheck();assert.equal(await selection.locator('#send-radio').isDisabled(),true);assert.match(await selection.locator('#radio-note').innerText(),/Select a first-hand observation/);await record('empty observation selection stays blocked',{state:await state(selection)});
 // Different hidden remote work/departure facts cannot affect visible offer labels.
 const twinA=await pageFor('remote-twin-a',player.createGame({...opts(.9751),inletMinutes:2,launchAt:27}));const twinB=await pageFor('remote-twin-b',player.createGame({...opts(.9751),inletMinutes:14,launchAt:15}));assert.equal((await state(twinA)).bodyText,(await state(twinB)).bodyText);await reportPanel(twinA);await reportPanel(twinB);assert.equal((await state(twinA)).bodyText,(await state(twinB)).bodyText);await record('hidden remote twins have identical complete DOM text and report offers',{});
 let repair=player.advanceGame(request(player.createGame(opts(.92)),{task:'inspect'}),1);const rp=await pageFor('repair-options',repair);assert.match(await rp.locator('[data-choice=repair-full]').innerText(),/Try the full repair\s+6 min/);assert.match(await rp.locator('[data-choice=repair-one]').innerText(),/^Repair for 1 minute\s+1 min/);assert.equal(await rp.locator('[data-choice=repair-one]').isEnabled(),true);await screen(rp,'repair-options');await record('full interval uncertainty preserves one-minute caller choice and distinct costs',{state:await state(rp)});
 // Preserve the existing real receipt pause and independent Continue/Stop decisions.
 let release=player.createGame({valveMinutes:6,inletMinutes:14,launchAt:15,channelMode:'bounded',channelOverrides:{'receiver:2':6}});release=player.advanceGame(request(release,{task:'inspect'}),1);release=request(release,{task:'repair'});while(player.getGameView(release).job)release=player.advanceToNextEvent(release);release=request(release,{task:'release'});
 for(const action of ['stop','continue']){const p=await pageFor('report-agency-'+action,release);await p.locator('#next-event').click();const receipt=await state(p),v=player.getGameView(stored(receipt));assert.equal(v.now,8);assert.equal(v.job.task,'release');assert.equal(v.job.elapsed,1);assert.equal(v.inventory.water.reserved,2);assert.equal(receipt.selected,'tab-notebook');assert.equal(receipt.focus.id,'tab-notebook');await screen(p,'arrival-'+action);const saved=receipt.storage;await p.locator('#tab-work').click();await p.locator('#tab-notebook').click();assert.equal((await state(p)).storage,saved);await p.locator(action==='stop'?'#stop':'#next-event').click();const after=player.getGameView(stored(await state(p)));assert.equal(after.paid.release,action==='stop'?1:2);assert.equal(after.inventory.water.available,action==='stop'?2:0);assert.equal(after.now,action==='stop'?8:9);await record('report arrival preserves explicit '+action+' agency',{receipt,after,layout:await controlsReachable(p)});}
}catch(error){results.fatal={message:error.message,stack:error.stack};}
finally{await capture('after');results.sourceStable=paths.every(p=>results.sources.before[p].sha256===results.sources.after[p].sha256);await fs.writeFile(dir+'/results.json',JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify({checks:results.checks.map(c=>c.name),findings:results.findings,browserErrors:results.browserErrors,fatal:results.fatal,sourceStable:results.sourceStable,screenshots:results.screenshots.length},null,2));}
