import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspace,catalog,action,message,episode} from '../examples/experienced-person/setup.js';
import {deliverExperienceMessage,receiveExperienceEpisode,beginExperienceAttempt,advanceExperienceAttempt,finishExperienceAttempt,getExperienceView,exportExperienceWorkspace,restoreExperienceWorkspace,advanceExperience,advanceExperienceCalendar} from '../src/experience/workspace.js';
const clone=x=>JSON.parse(JSON.stringify(x));
function finish(state,status='completed'){return finishExperienceAttempt(state,{attemptId:state.actor.person.sustained.situated.human.pending.id,status,mealConsumed:false},catalog);}
function read(state,id,minutes=2,status='completed'){state=beginExperienceAttempt(state,{action:action('read',minutes),attentionMessageId:id,purposeId:'deliver'},catalog);state=advanceExperienceAttempt(state,minutes,catalog);return finish(state,status);}
test('delivered message stays unread until selected actual paid work completes',()=>{let state=deliverExperienceMessage(createWorkspace(),message(),catalog);assert.equal(getExperienceView(state,catalog).actor.developing.beliefs.beliefs[0].status,'unknown');state=read(state,'gate');const view=getExperienceView(state,catalog);assert.equal(view.now,2);assert.equal(view.actor.developing.beliefs.beliefs.find(b=>b.propositionId==='gateOpen').value,true);assert.equal(state.actor.person.lastAttempt.elapsedMinutes,2);assert.throws(()=>read(state,'gate'),/processed|available|read/i);});
test('two processed premises derive a conclusion without manufacturing original evidence',()=>{let state=deliverExperienceMessage(createWorkspace(),message(),catalog);state=deliverExperienceMessage(state,message('permit','permitValid'),catalog);state=read(state,'gate');assert.equal(getExperienceView(state,catalog).reasoning.conclusions.find(c=>c.propositionId==='directAllowed').status,'unknown');state=read(state,'permit');assert.equal(getExperienceView(state,catalog).reasoning.conclusions.find(c=>c.propositionId==='directAllowed').status,'true');assert.equal(state.actor.person.beliefs.receipts.length,2);state=advanceExperience(state,{to:100,mode:'awake'},catalog);assert.equal(getExperienceView(state,catalog).reasoning.conclusions.find(c=>c.propositionId==='directAllowed').status,'unknown');});
test('interruption and expiry during attention retain paid cost without learning content',()=>{for(const expired of [false,true]){let state=deliverExperienceMessage(createWorkspace(),message('gate','gateOpen',true,expired?1:100),catalog);state=read(state,'gate',2,expired?'completed':'interrupted');assert.equal(state.actor.person.sustained.situated.now,2);assert.equal(state.actor.person.beliefs.receipts.length,0);}});
test('selected target and partial paid progress survive JSON continuation while later messages cannot replace it',()=>{let state=deliverExperienceMessage(createWorkspace(),message(),catalog);state=beginExperienceAttempt(state,{action:action('read',2),attentionMessageId:'gate'},catalog);state=advanceExperienceAttempt(state,1,catalog);state=deliverExperienceMessage(state,{...message('permit','permitValid'),deliveredAt:1},catalog);const restored=restoreExperienceWorkspace(clone(exportExperienceWorkspace(state,catalog)),catalog,'courier');assert.deepEqual(finish(advanceExperienceAttempt(restored,1,catalog)),finish(advanceExperienceAttempt(state,1,catalog)));const result=finish(advanceExperienceAttempt(restored,1,catalog));assert.deepEqual(result.actor.person.beliefs.receipts.map(x=>x.propositionId),['gateOpen']);});
test('historical recall preserves original times and never refreshes beliefs',()=>{let state=receiveExperienceEpisode(createWorkspace(),episode(),catalog);state=advanceExperience(state,{to:20,mode:'awake'},catalog);const view=getExperienceView(state,catalog,{contextId:'route'});assert.equal(view.memories.episodes[0].occurredAt,0);assert.equal(view.memories.episodes[0].receivedAt,0);assert.equal(state.actor.person.beliefs.receipts.length,0);assert.equal(getExperienceView(state,catalog,{contextId:'warehouse'}).memories.episodes.length,0);});
test('invalid selection and cross-owner saves reject atomically; calendar cannot skip pending attention',()=>{const state=deliverExperienceMessage(createWorkspace(),message(),catalog),before=clone(state);assert.throws(()=>beginExperienceAttempt(state,{action:action('read',1),attentionMessageId:'gate'},catalog),/duration|minimum|review/i);assert.deepEqual(state,before);const pending=beginExperienceAttempt(state,{action:action('read',2),attentionMessageId:'gate'},catalog);assert.throws(()=>advanceExperienceCalendar(pending,{toDay:1,kind:'unmodeled'},catalog),/pending/i);assert.throws(()=>restoreExperienceWorkspace(exportExperienceWorkspace(state,catalog),catalog,'dispatcher'),/owner/i);});

test('an invalid correction cannot start paid review and message IDs cannot be injected as observations',async()=>{const {updateExperienceActor}=await import('../src/experience/workspace.js');let state=deliverExperienceMessage(createWorkspace(),{...message(),correctsReceiptId:'absent'},catalog);assert.throws(()=>beginExperienceAttempt(state,{action:action('read',2),attentionMessageId:'gate'},catalog),/correction|target/i);assert.equal(state.actor.person.sustained.situated.human.pending,null);state=deliverExperienceMessage(createWorkspace(),message(),catalog);assert.throws(()=>updateExperienceActor(state,{kind:'evidence',input:{receiptId:'gate',propositionId:'gateOpen',sourceId:'dispatcher',originId:'dispatcher',value:true,observedAt:0,receivedAt:0,expiresAt:100,correctsReceiptId:null}},catalog),/unread|reserved|message/i);});
test('restoration rejects message/evidence disagreement and a processing charged to pending work',()=>{let state=read(deliverExperienceMessage(createWorkspace(),message(),catalog),'gate');const mismatch=exportExperienceWorkspace(state,catalog);mismatch.workspace.actor.person.beliefs.receipts[0].value=false;assert.throws(()=>restoreExperienceWorkspace(mismatch,catalog,'courier'),/matching|message/i);state=beginExperienceAttempt(state,{action:action('read',2)},catalog);const forged=exportExperienceWorkspace(state,catalog);forged.workspace.attention.processings[0].attemptId=state.actor.person.sustained.situated.human.pending.id;assert.throws(()=>restoreExperienceWorkspace(forged,catalog,'courier'),/payment|paid|pending/i);});
