import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
const path=new URL('../src/games/service-plan.js',import.meta.url);
test('new shared clinic host exists independently of the frozen service host',()=>assert.ok(existsSync(path),'Missing new shared-plan host'));
const h=existsSync(path)?await import(path):null;
const json=x=>JSON.parse(JSON.stringify(x));
const ask=(s,a,t)=>{s=h.requestTask(s,a,t);assert.equal(s.lastResponse.accepted,true,s.lastResponse.reason);return s;};
function prefix(at=37){let s=ask(h.createServicePlan(),'keeper','meal');s=h.advanceTo(s,4);s=ask(s,'keeper','gate');s=h.advanceTo(s,10);s=ask(s,'keeper','gate');s=h.advanceTo(s,16);s=ask(s,'keeper','salvage');s=h.advanceTo(s,24);s=ask(s,'keeper','rest');return h.advanceTo(s,at);}
const safe={pumpStartAt:39,readyBy:45,waitUntil:45,fallback:'cart'};
const risk={pumpStartAt:47,readyBy:53,waitUntil:53,fallback:'none'};
const propose=(s,t)=>{s=h.proposePlan(s,t);assert.equal(s.lastResponse.accepted,true,s.lastResponse.reason);return s;};
if(h){
test('listening and term acceptance are separate and both people pay active time',()=>{let s=prefix(),before=json(s);s=propose(s,safe);assert.equal(s.coordination.current,null);assert.equal(s.coordination.pending.invitationAccepted,true);assert.equal(s.jobs.partner.task,'discuss');assert.equal(s.jobs.keeper.task,'discuss');s=h.advanceTo(s,38);assert.equal(s.coordination.current,null);for(const a of ['keeper','partner']){assert.equal(s.paidByActor[a].discuss,1);assert.ok(s.people[a].body.fatigue>before.people[a].body.fatigue);}s=h.advanceTo(s,39);assert.equal(s.coordination.current.status,'active');assert.equal(s.coordination.lastResponse.stage,'terms');assert.equal(s.coordination.current.respondedAt,39);assert.deepEqual(s.parts,before.parts);assert.deepEqual(before,prefix());});
test('short hold enables actual full delivery and records readiness separately from arrival',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'keeper','pump');s=h.advanceTo(s,45);assert.equal(s.coordination.current.actualReadyAt,45);assert.equal(s.coordination.current.contribution.status,'fulfilled');assert.equal(s.delivery,null);assert.equal(s.jobs.partner.task,'deliver');s=h.advanceTo(s,64);assert.deepEqual(s.delivery,{at:51,route:'deliver',units:2});assert.equal(s.outcome.allService,true);assert.equal(s.coordination.current.status,'fulfilled');assert.equal(s.paidByActor.partner.discuss,2);});
test('missed short promise retains a feasible one-unit fallback at45',()=>{let s=h.advanceTo(propose(prefix(),safe),64);assert.deepEqual(s.delivery,{at:63,route:'cart',units:1});assert.equal(s.coordination.current.contribution.status,'missed');assert.equal(s.coordination.slot.departedAt,45);});
test('busy invitation never stops work and unsuitable terms cost the completed discussion',()=>{let s=h.advanceTo(h.createServicePlan(),24),jobs=json(s.jobs);s=h.proposePlan(s,safe);assert.equal(s.lastResponse.code,'BUSY');assert.deepEqual(s.jobs,jobs);s=h.advanceTo(propose(prefix(),{...safe,pumpStartAt:44}),39);assert.equal(s.coordination.current,null);assert.equal(s.coordination.lastResponse.accepted,false);assert.equal(s.paid.discuss,4);});
test('interruption retains paid active minutes and no accepted terms',()=>{let s=h.advanceTo(propose(prefix(),safe),38),body=json(s.people);s=h.interruptDiscussion(s,'partner');assert.equal(s.coordination.current,null);assert.equal(s.coordination.pending,null);assert.deepEqual(s.people.keeper.body,body.keeper.body);assert.equal(s.paid.discuss,2);assert.equal(s.jobs.keeper.task,'idle');assert.equal(s.jobs.partner.task,'idle');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('useful accepted revision prevents old45cart and preserves actual carried work',()=>{let s=h.advanceTo(propose(prefix(),safe),39);const id=s.coordination.current.id;s=ask(s,'keeper','rest');s=h.advanceTo(s,41);s=h.interruptTask(s,'keeper');s=propose(s,risk);assert.equal(s.coordination.current.id,id);s=h.advanceTo(s,43);assert.equal(s.coordination.current.revisionOf,id);s=ask(s,'keeper','rest');s=h.advanceTo(s,47);s=h.interruptTask(s,'keeper');s=ask(s,'keeper','pump');s=h.advanceTo(s,64);assert.deepEqual(s.delivery,{at:59,route:'deliver',units:2});assert.equal(s.paidByActor.partner.discuss,4);assert.equal(s.coordination.current.contribution.status,'fulfilled');});
test('refused and interrupted revisions preserve original accepted terms',()=>{let s=h.advanceTo(propose(prefix(),safe),39),old=json(s.coordination.current);s=h.advanceTo(propose(s,{...risk,pumpStartAt:53}),41);assert.deepEqual(s.coordination.current,old);assert.equal(s.coordination.lastResponse.accepted,false);s=propose(s,risk);s=h.advanceTo(s,42);s=h.interruptDiscussion(s);assert.deepEqual(s.coordination.current,old);s=h.advanceTo(s,64);assert.equal(s.delivery.at,63);});
test('withdrawal retracts own promise but does not stop work or erase clinic obligation',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'keeper','pump');const owned=json(s.jobs.keeper);s=h.withdrawContribution(s);assert.deepEqual(s.jobs.keeper,owned);assert.equal(s.coordination.current.status,'withdrawn');assert.equal(s.coordination.current.contribution.status,'withdrawn');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,1);assert.equal(s.delivery.at,60);});
test('old response cannot accept a new revision or duplicate acceptance',()=>{let s=propose(prefix(),safe),receipt=json(s.coordination.pending.receipt);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='EARLY_RESPONSE');s=h.advanceTo(s,39);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='STALE_RESPONSE');s=propose(s,risk);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='STALE_RESPONSE');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('revision exactly at old expiry cannot revive it or delay the45cart',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=h.advanceTo(s,43);s=propose(s,risk);s=h.advanceTo(s,45);assert.equal(s.coordination.pending,null);assert.equal(s.coordination.current.terms.waitUntil,45);assert.equal(s.jobs.partner.task,'cart');assert.equal(s.coordination.lastResponse.code,'EXPIRED');});
test('clinic receiving slot survives an interrupted departure and rejects renegotiation',()=>{let s=prefix(30);s=ask(s,'partner','cart');s=h.advanceTo(s,31);s=h.interruptTask(s,'partner');assert.equal(s.coordination.slot.status,'abandoned');s=h.requestTask(s,'keeper','cart');assert.equal(s.lastResponse.code,'CLINIC_SLOT_USED');s=h.proposePlan(s,{pumpStartAt:33,readyBy:39,waitUntil:45,fallback:'cart'});assert.equal(s.lastResponse.code,'CLINIC_SLOT_USED');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,0);});
test('save identity is independent and forged promises cannot alter deterministic replay',()=>{let s=h.advanceTo(propose(prefix(),safe),38),saved=h.exportServicePlan(s);assert.equal(saved.format,'human-service-plan');assert.deepEqual(h.restoreServicePlan(json(saved)),s);for(const mutate of [x=>x.state.coordination.pending.terms.readyBy++,x=>x.state.parts.keeper++,x=>x.state.coordination.current={},x=>x.state.paid.discuss++,x=>x.state.clock.queue.reverse(),x=>x.format='human-service-day']){let forged=json(saved);mutate(forged);assert.throws(()=>h.restoreServicePlan(forged));}assert.deepEqual(h.advanceTo(h.restoreServicePlan(json(saved)),64),h.advanceTo(s,64));});
}
if(h){
test('a requested partner job crossing the hold deadline is not compelled to stop',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'partner','rest');s=h.advanceTo(s,40);s=h.interruptTask(s,'partner');s=ask(s,'partner','rest');s=h.advanceTo(s,45);assert.equal(s.jobs.partner.task,'rest');assert.equal(s.jobs.partner.endsAt,46);assert.equal(s.coordination.current.status,'expired');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,0);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('completed readiness retains its actual earlier timestamp and cannot be retracted',()=>{let s=prefix(30);s=ask(s,'partner','rest');s=ask(s,'keeper','pump');s=h.advanceTo(s,35);s=h.interruptTask(s,'partner');s=ask(s,'partner','rest');s=h.advanceTo(s,36);s=h.interruptTask(s,'partner');s=propose(s,{pumpStartAt:38,readyBy:44,waitUntil:45,fallback:'cart'});s=h.advanceTo(s,38);assert.equal(s.coordination.current.actualReadyAt,36);assert.equal(s.coordination.current.contribution.fulfilledAt,36);assert.equal(h.getServicePlanView(s).coordination.readiness.readyAt,36);assert.equal(s.jobs.partner.task,'deliver');});
test('an already fulfilled contribution is not erased by withdrawal during a requested recovery',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'keeper','pump');s=ask(s,'partner','rest');s=h.advanceTo(s,44);s=h.interruptTask(s,'partner');s=ask(s,'partner','rest');s=h.advanceTo(s,45);const prior=json(s.coordination.current.contribution);s=h.withdrawContribution(s);assert.deepEqual(s.coordination.current.contribution,prior);assert.equal(s.lastResponse.accepted,false);});
test('an accepted risky forecast does not supply unperformed recovery or guarantee capacity',()=>{const source=JSON.parse(readFileSync(new URL('../artifacts/service-day/late-timed-request-control.json',import.meta.url)));let s=h.createServicePlan();for(const c of source.checkpointAt41.commands){if(c.type==='request')s=h.requestTask(s,c.actor,c.task);else if(c.type==='stop')s=h.interruptTask(s,c.actor);else s=h.advanceTo(s,c.to);}assert.equal(s.clock.now,41);s=h.advanceTo(propose(s,risk),43);assert.equal(s.coordination.current.status,'active');s=h.advanceTo(s,47);s=h.requestTask(s,'keeper','pump');assert.equal(s.lastResponse.code,'CAPACITY');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,0);assert.equal(s.coordination.current.contribution.status,'missed');assert.equal(s.paidByActor.keeper.rest,3);});
test('risky wait uses the retained gate checkpoint and actual paid four-minute rest',()=>{const source=JSON.parse(readFileSync(new URL('../artifacts/service-day/late-timed-request-control.json',import.meta.url)));let s=h.createServicePlan();for(const c of source.checkpointAt41.commands){if(c.type==='request')s=h.requestTask(s,c.actor,c.task);else if(c.type==='stop')s=h.interruptTask(s,c.actor);else s=h.advanceTo(s,c.to);}s=h.advanceTo(propose(s,risk),43);s=ask(s,'keeper','rest');s=h.advanceTo(s,47);s=h.interruptTask(s,'keeper');s=ask(s,'keeper','pump');s=h.advanceTo(s,64);assert.deepEqual(s.delivery,{at:59,route:'deliver',units:2});assert.equal(s.paidByActor.keeper.rest,7);assert.equal(s.paidByActor.partner.discuss,2);assert.equal(s.paidByActor.partner.rest,5); /* Self-chosen recovery after arrival59 through closing64. */});
test('closing still defeats a tied delivery and records a closed receiving slot',()=>{let s=prefix(37);s=ask(s,'partner','rest');s=h.advanceTo(s,42);s=h.interruptTask(s,'partner');s=ask(s,'partner','rest');s=h.advanceTo(s,46);s=h.interruptTask(s,'partner');s=ask(s,'partner','cart');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,0);assert.equal(s.delivery,null);assert.equal(s.paidByActor.partner.cart,18);assert.equal(s.coordination.slot.status,'closed');});
test('same-minute repeated invitation refusals coalesce without consuming proposal identities',()=>{let s=h.advanceTo(h.createServicePlan(),24);for(let i=0;i<3000;i++)s=h.proposePlan(s,i%2?safe:risk);assert.equal(s.coordination.nextId,1);assert.equal(s.commands.length,2);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('capped discussions retain sufficient interruption and closing budget',()=>{let s=prefix();for(let i=0;i<200;i++){try{s=propose(s,safe);s=h.interruptDiscussion(s);}catch(e){assert.equal(e.code,'COMMAND_LIMIT');break;}}s=h.advanceTo(s,64);assert.equal(s.outcome.at,64);assert.ok(JSON.stringify(h.exportServicePlan(s)).length<65536);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('all time drivers resume equal through accepted and interrupted revisions',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=propose(s,risk);s=h.advanceTo(s,40);s=h.interruptDiscussion(s);s=propose(s,risk);let stepped=s,event=s;for(let n=s.clock.now+1;n<=64;n++)stepped=h.advanceTo(stepped,n);while(!event.outcome)event=h.advanceTo(event,h.nextVisibleEvent(event));const lump=h.advanceTo(s,64);assert.deepEqual(h.exportServicePlan(lump),h.exportServicePlan(stepped));assert.deepEqual(h.exportServicePlan(event),h.exportServicePlan(lump));});
}
if(h){
test('cross-family latest refusal channels coalesce and resume without losing either response',()=>{let s=h.createServicePlan();for(let i=0;i<500;i++){s=h.proposePlan(s,safe);s=h.requestTask(s,'partner','share');s=h.withdrawContribution(s);s=h.requestTask(s,'partner','divert');}assert.ok(s.commands.length<=2);assert.equal(s.clock.now,0);assert.equal(s.coordination.nextId,1);assert.equal(s.coordination.lastResponse.code,'NO_ACTIVE_PLAN');assert.equal(s.lastResponse.code,'CLINIC_RESERVE');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);s=h.advanceTo(s,24);for(let i=0;i<500;i++){s=h.interruptTask(s,'partner');s=h.proposePlan(s,safe);s=h.requestTask(s,'keeper','pump');}assert.ok(s.commands.length<=5);assert.equal(s.coordination.lastResponse.code,'BUSY');assert.equal(s.lastResponse.code,'TARGET_BUSY');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);s=h.advanceTo(s,64);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
}
if(h){
test('a predecessor deadline during discussion stops only the meeting and retains its paid partial cost',()=>{const early={pumpStartAt:32,readyBy:38,waitUntil:40,fallback:'cart'};let s=h.advanceTo(propose(prefix(30),early),32);s=h.advanceTo(s,39);s=propose(s,{pumpStartAt:43,readyBy:49,waitUntil:49,fallback:'none'});s=h.advanceTo(s,40);assert.equal(s.coordination.pending,null);assert.equal(s.coordination.current.terms.waitUntil,40);assert.equal(s.jobs.partner.task,'cart');assert.equal(s.paidByActor.keeper.discuss,3);assert.equal(s.paidByActor.partner.discuss,3);assert.equal(s.coordination.lastResponse.code,'EXPIRED');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('cross-family refusals at the final request budget leave stops and closing usable',()=>{let s=h.createServicePlan();while(h.getServicePlanView(s).remainingCommands>5){s=ask(s,'keeper','rest');s=h.interruptTask(s,'keeper');}s=h.advanceTo(s,24);s=ask(s,'keeper','rest');for(let i=0;i<500;i++){s=h.proposePlan(s,safe);s=h.requestTask(s,'keeper','gate');s=h.withdrawContribution(s);s=h.interruptTask(s,'partner');}s=h.interruptTask(s,'keeper');s=h.advanceTo(s,64);assert.equal(s.outcome.at,64);assert.ok(JSON.stringify(h.exportServicePlan(s)).length<65536);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('owned spare and inlet supply are prerequisites for consent, not implied by a promise',()=>{let s=h.advanceTo(h.createServicePlan(),30);s=h.advanceTo(propose(s,{pumpStartAt:32,readyBy:38,waitUntil:45,fallback:'cart'}),32);assert.equal(s.coordination.lastResponse.code,'NO_SUPPLY');s=ask(h.createServicePlan(),'keeper','meal');s=h.advanceTo(s,4);s=ask(s,'keeper','gate');s=h.advanceTo(s,10);s=ask(s,'keeper','gate');s=h.advanceTo(s,30);s=h.advanceTo(propose(s,{pumpStartAt:32,readyBy:38,waitUntil:45,fallback:'cart'}),32);assert.equal(s.coordination.lastResponse.code,'MISSING_PARTS');assert.equal(s.coordination.current,null);assert.equal(s.parts.partner,0);});
test('malformed terms and hostile save structures reject before executing accessors or work',()=>{const s=prefix(),before=json(s);let called=0;const terms={get pumpStartAt(){called++;return 39;},readyBy:45,waitUntil:45,fallback:'cart'};assert.throws(()=>h.proposePlan(s,terms));assert.equal(called,0);for(const t of [{...safe,extra:true},{...safe,readyBy:45.5},{...safe,pumpStartAt:-0},{...safe,fallback:'teleport'}])assert.throws(()=>h.proposePlan(s,t));assert.deepEqual(s,before);const saved=h.exportServicePlan(s);for(const mutate of [x=>x.state.coordination.slot={actor:'keeper',route:'cart',departedAt:30,arrivedAt:null,status:'abandoned'},x=>x.state.coordination.nextId++,x=>x.state.coordination.readyAt=30,x=>x.commands=[{type:'refusal',command:{type:'request',actor:'keeper',task:'rest'}}],x=>x.commands=Array(257).fill({type:'advance',to:0})]){const n=json(saved);mutate(n);assert.throws(()=>h.restoreServicePlan(n));}});
test('mixed actual commands including plan edits preserve replay and bounded state over many paid days',()=>{let seed=8231;const draw=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};for(let run=0;run<30;run++){let s=prefix(30);for(let i=0;i<60&&!s.outcome;i++){const a=draw(2)?'keeper':'partner',k=draw(7);try{if(k===0)s=h.proposePlan(s,{pumpStartAt:Math.min(58,s.clock.now+2),readyBy:Math.min(64,s.clock.now+8),waitUntil:draw(2)?45:53,fallback:draw(2)?'cart':'none'});else if(k===1&&s.coordination.pending)s=h.interruptDiscussion(s,a);else if(k===2)s=h.withdrawContribution(s);else if(k===3&&s.jobs[a].task!=='idle')s=h.interruptTask(s,a);else if(k===4)s=h.requestTask(s,a,Object.keys(h.SERVICE_TASKS)[draw(10)]);else s=h.advanceTo(s,Math.min(64,s.clock.now+1+draw(5)));}catch(e){assert.equal(e.code,'COMMAND_LIMIT');}assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);}s=h.advanceTo(s,64);assert.ok(JSON.stringify(h.exportServicePlan(s)).length<65536);}});
}
if(h){
test('visible event pauses at an earlier promised readiness before a longer accepted hold expires',()=>{let s=h.advanceTo(propose(prefix(),{pumpStartAt:39,readyBy:45,waitUntil:53,fallback:'none'}),39);assert.equal(h.nextVisibleEvent(s),45);s=h.advanceTo(s,h.nextVisibleEvent(s));assert.equal(s.coordination.current.contribution.status,'missed');assert.equal(s.coordination.current.status,'active');assert.equal(h.nextVisibleEvent(s),53);});
test('visible event exposes promised pump start so paid rest can stop at its actual planned boundary',()=>{let s=h.advanceTo(propose(prefix(41),risk),43);s=ask(s,'keeper','rest');assert.equal(s.jobs.keeper.endsAt,49);assert.equal(h.nextVisibleEvent(s),47);s=h.advanceTo(s,47);assert.equal(s.jobs.keeper.task,'rest');assert.equal(s.paidByActor.keeper.rest,10);s=h.interruptTask(s,'keeper');s=ask(s,'keeper','pump');assert.equal(s.jobs.keeper.endsAt,53);});
}
if(h){
function padTo249(s){while(s.commands.length<249){if(s.commands.length===248)s=h.requestTask(s,'partner','share');else{s=ask(s,'keeper','rest');s=h.interruptTask(s,'keeper');}}assert.equal(s.commands.length,249);return s;}
function partialAtCap(){let s=propose(padTo249(prefix()),safe);s=h.requestTask(s,'keeper','rest');s=h.withdrawContribution(s);return h.advanceTo(s,38);}
test('cap reserves a unilateral partial-discussion stop after both refusal channels and elapsed time',()=>{let s=partialAtCap();assert.equal(s.commands.length,253);assert.equal(h.getServicePlanView(s).coordination.canInterrupt,true);s=h.interruptDiscussion(s,'partner');assert.equal(s.coordination.pending,null);assert.equal(s.paid.discuss,2);assert.equal(s.coordination.current,null);s=h.advanceTo(s,64);assert.equal(s.paid.discuss,2);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('cap retains separate stops for both requested jobs across a partial advance',()=>{let s=padTo249(h.createServicePlan());s=ask(s,'keeper','rest');s=ask(s,'partner','rest');assert.throws(()=>h.withdrawContribution(s),e=>e.code==='COMMAND_LIMIT');s=h.advanceTo(s,1);s=h.interruptTask(s,'keeper');s=h.advanceTo(s,2);assert.equal(s.commands.length,254);s=h.interruptTask(s,'partner');assert.equal(s.lastResponse.accepted,true);assert.equal(s.paidByActor.partner.rest,2);s=h.advanceTo(s,64);assert.equal(s.commands.length,256);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('a cap successor refusal cannot consume later interruption or accepted-plan withdrawal',()=>{let s=partialAtCap();const before=json(s);assert.throws(()=>h.withdrawContribution(s),e=>e.code==='COMMAND_LIMIT');assert.deepEqual(s,before);assert.equal(h.getServicePlanView(s).coordination.canInterrupt,true);let stopped=h.interruptDiscussion(s);stopped=h.advanceTo(stopped,64);assert.equal(stopped.paid.discuss,2);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(stopped))),stopped);s=h.advanceTo(s,39);assert.equal(h.getServicePlanView(s).coordination.canWithdraw,true);s=h.withdrawContribution(s);assert.equal(s.coordination.current.status,'withdrawn');s=h.advanceTo(s,64);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
}
if(h){
test('cap preserves both requested stops and promise withdrawal at three different paid minutes',()=>{let s=h.advanceTo(propose(prefix(),safe),39);while(s.commands.length<247){if(s.commands.length===246)s=h.requestTask(s,'partner','share');else{s=ask(s,'keeper','rest');s=h.interruptTask(s,'keeper');}}s=ask(s,'keeper','rest');s=ask(s,'partner','rest');assert.equal(s.commands.length,249);s=h.advanceTo(s,40);s=h.interruptTask(s,'keeper');s=h.advanceTo(s,41);assert.equal(h.getServicePlanView(s).coordination.canWithdraw,true);s=h.withdrawContribution(s);s=h.advanceTo(s,42);s=h.interruptTask(s,'partner');assert.equal(s.paidByActor.partner.rest,3);assert.equal(s.coordination.current.status,'withdrawn');s=h.advanceTo(s,64);assert.equal(s.commands.length,256);assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
}
