import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
const path=new URL('../src/games/service-plan.js',import.meta.url);
test('new shared clinic host exists independently of the frozen service host',()=>assert.ok(existsSync(path),'Missing new shared-plan host'));
const h=existsSync(path)?await import(path):null;
const json=x=>JSON.parse(JSON.stringify(x));
const ask=(s,a,t)=>{s=h.requestTask(s,a,t);assert.equal(s.lastResponse.accepted,true,s.lastResponse.reason);return s;};
function prefix(at=37){let s=ask(h.createServicePlan(),'keeper','meal');s=h.advanceTo(s,4);s=ask(s,'keeper','gate');s=h.advanceTo(s,10);s=ask(s,'keeper','gate');s=h.advanceTo(s,16);s=ask(s,'keeper','salvage');s=h.advanceTo(s,24);s=ask(s,'keeper','rest');return h.advanceTo(s,at);}
const safe={pumpStartAt:39,readyBy:45,waitUntil:45,fallback:'cart'};
const risk={pumpStartAt:47,readyBy:53,waitUntil:53,fallback:'none'};
const propose=(s,t)=>{s=h.proposePlan(s,t);assert.equal(s.lastResponse.accepted,true,s.lastResponse.reason);return s;};
if(h){
test('listening and term acceptance are separate and both people pay active time',()=>{let s=prefix(),before=json(s);s=propose(s,safe);assert.equal(s.coordination.current,null);assert.equal(s.coordination.pending.invitationAccepted,true);assert.equal(s.jobs.partner.task,'discuss');assert.equal(s.jobs.keeper.task,'discuss');s=h.advanceTo(s,38);assert.equal(s.coordination.current,null);for(const a of ['keeper','partner']){assert.equal(s.paidByActor[a].discuss,1);assert.ok(s.people[a].body.fatigue>before.people[a].body.fatigue);}s=h.advanceTo(s,39);assert.equal(s.coordination.current.status,'active');assert.equal(s.coordination.lastResponse.stage,'terms');assert.equal(s.coordination.current.respondedAt,39);assert.deepEqual(s.parts,before.parts);assert.deepEqual(before,prefix());});
test('short hold enables actual full delivery and records readiness separately from arrival',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'keeper','pump');s=h.advanceTo(s,45);assert.equal(s.coordination.current.actualReadyAt,45);assert.equal(s.coordination.current.contribution.status,'fulfilled');assert.equal(s.delivery,null);assert.equal(s.jobs.partner.task,'deliver');s=h.advanceTo(s,64);assert.deepEqual(s.delivery,{at:51,route:'deliver',units:2});assert.equal(s.outcome.allService,true);assert.equal(s.coordination.current.status,'fulfilled');assert.equal(s.paidByActor.partner.discuss,2);});
test('missed short promise retains a feasible one-unit fallback at45',()=>{let s=h.advanceTo(propose(prefix(),safe),64);assert.deepEqual(s.delivery,{at:63,route:'cart',units:1});assert.equal(s.coordination.current.contribution.status,'missed');assert.equal(s.coordination.slot.departedAt,45);});
test('busy invitation never stops work and unsuitable terms cost the completed discussion',()=>{let s=h.advanceTo(h.createServicePlan(),24),jobs=json(s.jobs);s=h.proposePlan(s,safe);assert.equal(s.lastResponse.code,'BUSY');assert.deepEqual(s.jobs,jobs);s=h.advanceTo(propose(prefix(),{...safe,pumpStartAt:44}),39);assert.equal(s.coordination.current,null);assert.equal(s.coordination.lastResponse.accepted,false);assert.equal(s.paid.discuss,4);});
test('interruption retains paid active minutes and no accepted terms',()=>{let s=h.advanceTo(propose(prefix(),safe),38),body=json(s.people);s=h.interruptDiscussion(s,'partner');assert.equal(s.coordination.current,null);assert.equal(s.coordination.pending,null);assert.deepEqual(s.people.keeper.body,body.keeper.body);assert.equal(s.paid.discuss,2);assert.equal(s.jobs.keeper.task,'idle');assert.equal(s.jobs.partner.task,'idle');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('useful accepted revision prevents old45cart and preserves actual carried work',()=>{let s=h.advanceTo(propose(prefix(),safe),39);const id=s.coordination.current.id;s=ask(s,'keeper','rest');s=h.advanceTo(s,41);s=h.interruptTask(s,'keeper');s=propose(s,risk);assert.equal(s.coordination.current.id,id);s=h.advanceTo(s,43);assert.equal(s.coordination.current.revisionOf,id);s=ask(s,'keeper','rest');s=h.advanceTo(s,47);s=h.interruptTask(s,'keeper');s=ask(s,'keeper','pump');s=h.advanceTo(s,64);assert.deepEqual(s.delivery,{at:59,route:'deliver',units:2});assert.equal(s.paidByActor.partner.discuss,4);assert.equal(s.coordination.current.contribution.status,'fulfilled');});
test('refused and interrupted revisions preserve original accepted terms',()=>{let s=h.advanceTo(propose(prefix(),safe),39),old=json(s.coordination.current);s=h.advanceTo(propose(s,{...risk,pumpStartAt:53}),41);assert.deepEqual(s.coordination.current,old);assert.equal(s.coordination.lastResponse.accepted,false);s=propose(s,risk);s=h.advanceTo(s,42);s=h.interruptDiscussion(s);assert.deepEqual(s.coordination.current,old);s=h.advanceTo(s,64);assert.equal(s.delivery.at,63);});
test('withdrawal retracts own promise but does not stop work or erase clinic obligation',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=ask(s,'keeper','pump');const owned=json(s.jobs.keeper);s=h.withdrawContribution(s);assert.deepEqual(s.jobs.keeper,owned);assert.equal(s.coordination.current.status,'withdrawn');assert.equal(s.coordination.current.contribution.status,'withdrawn');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,1);assert.equal(s.delivery.at,60);});
test('old response cannot accept a new revision or duplicate acceptance',()=>{let s=propose(prefix(),safe),receipt=json(s.coordination.pending.receipt);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='EARLY_RESPONSE');s=h.advanceTo(s,39);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='STALE_RESPONSE');s=propose(s,risk);assert.throws(()=>h.receivePlanResponse(s,receipt),e=>e.code==='STALE_RESPONSE');assert.deepEqual(h.restoreServicePlan(json(h.exportServicePlan(s))),s);});
test('revision exactly at old expiry cannot revive it or delay the45cart',()=>{let s=h.advanceTo(propose(prefix(),safe),39);s=h.advanceTo(s,43);s=propose(s,risk);s=h.advanceTo(s,45);assert.equal(s.coordination.pending,null);assert.equal(s.coordination.current.terms.waitUntil,45);assert.equal(s.jobs.partner.task,'cart');assert.equal(s.coordination.lastResponse.code,'EXPIRED');});
test('clinic receiving slot survives an interrupted departure and rejects renegotiation',()=>{let s=prefix(30);s=ask(s,'partner','cart');s=h.advanceTo(s,31);s=h.interruptTask(s,'partner');assert.equal(s.coordination.slot.status,'abandoned');s=h.requestTask(s,'keeper','cart');assert.equal(s.lastResponse.code,'CLINIC_SLOT_USED');s=h.proposePlan(s,{pumpStartAt:33,readyBy:39,waitUntil:45,fallback:'cart'});assert.equal(s.lastResponse.code,'CLINIC_SLOT_USED');s=h.advanceTo(s,64);assert.equal(s.outcome.clinicUnits,0);});
test('save identity is independent and forged promises cannot alter deterministic replay',()=>{let s=h.advanceTo(propose(prefix(),safe),38),saved=h.exportServicePlan(s);assert.equal(saved.format,'human-service-plan');assert.deepEqual(h.restoreServicePlan(json(saved)),s);for(const mutate of [x=>x.state.coordination.pending.terms.readyBy++,x=>x.state.parts.keeper++,x=>x.state.coordination.current={},x=>x.state.paid.discuss++,x=>x.state.clock.queue.reverse(),x=>x.format='human-service-day']){let forged=json(saved);mutate(forged);assert.throws(()=>h.restoreServicePlan(forged));}assert.deepEqual(h.advanceTo(h.restoreServicePlan(json(saved)),64),h.advanceTo(s,64));});
}
