import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {createAppServer} from './source/scripts/serve.js';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const root='/tmp/hf-game-hud-review-20260908/fixed',server=createAppServer({root:root+'/source'});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];let page,ctx;
async function fresh(game,width=375,height=667){if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width,height},acceptDownloads:true});page=await ctx.newPage();page.on('pageerror',e=>results.push({pageError:e.message}));await page.goto(origin+'/'+game+'/');await page.waitForTimeout(25);}
async function tab(n){await page.locator('#game-tab-'+n).click();}
async function state(){return page.evaluate(()=>({selected:document.querySelector('[role=tab][aria-selected=true]')?.textContent,focus:document.activeElement.id,play:document.getElementById('play')?.getAttribute('aria-pressed'),clock:document.querySelector('.hud-clock')?.textContent,panelHeight:document.querySelector('.game-content')?.clientHeight,docWidth:document.documentElement.scrollWidth,docHeight:document.documentElement.scrollHeight,save:Object.fromEntries(Object.entries(localStorage).sort())}));}
async function rect(id){return page.locator(id).evaluate(n=>{const r=n.getBoundingClientRect(),p=n.closest('[role=tabpanel]')?.getBoundingClientRect();return{visible:n.checkVisibility(),x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,panel:p?{y:p.y,bottom:p.bottom}:null};});}
try{
 await fresh('courtyard');for(let i=0;i<18;i++){await tab(0);await page.locator('[data-action=rest]').click();}await page.locator('#again').click();assert.equal((await state()).selected,'Actions');assert.equal((await state()).focus,'game-tab-0');assert(await page.locator('[data-action=draw-careful]').isVisible());results.push({case:'courtyard-restart-fixed',state:await state()});
 await fresh('courtyard');for(const action of ['draw-careful','pour','draw-careful'])await page.locator('[data-action='+action+']').click();assert.equal((await state()).selected,'Meryem');assert.equal((await state()).focus,'accept');const accept=await rect('#accept');assert(accept.visible&&accept.bottom<=667&&accept.y>=accept.panel.y&&accept.bottom<=accept.panel.bottom);results.push({case:'courtyard-proposal-fixed',state:await state(),accept});await page.screenshot({path:root+'/courtyard-proposal.png'});await page.locator('#refuse').click();assert.equal(await page.locator('#proposal').isVisible(),false);
 await fresh('commons-next');await page.locator('#next-event').click();assert.equal((await state()).selected,'Caches');assert.equal((await state()).focus,'checkpoint');for(const id of ['#checkpoint','#continue']){const r=await rect(id);assert(r.visible&&r.y>=0&&r.bottom<=667);results.push({case:'rain-ferry-fixed',id,rect:r});}await page.screenshot({path:root+'/rain-ferry.png'});await page.locator('#continue').click();assert.equal(await page.locator('#continue').isVisible(),false);await page.locator('#next-event').click();assert(await page.locator('#continue').isVisible());await page.locator('#continue').click();assert.equal((await state()).selected,'Journal');results.push({case:'rain-dusk-result-fixed',state:await state()});
 for(const game of ['commons','commons-next','watch','signals','service','service-plan']){await fresh(game);const work={commons:"#gather-choices [data-job=gather-timber]","commons-next":"#gather-choices [data-job=gather-timber]",watch:"#keeper-watch",signals:"#action-canal",service:"#keeper-gate","service-plan":"#keeper-pump"};await page.locator(work[game]).click();const before=await state();await page.locator('#play').click();await tab(4);assert.equal((await state()).play,'false');await page.waitForTimeout(1200);assert.equal((await state()).clock,before.clock);assert.deepEqual((await state()).save,before.save);await page.locator('#play').click();await page.locator('.episode-overview > summary').click();await page.waitForFunction(()=>document.getElementById('play').getAttribute('aria-pressed')==='false',{},{timeout:1000});assert.equal((await state()).play,'false');await page.waitForTimeout(1100);assert.equal((await state()).clock,before.clock);assert.deepEqual((await state()).save,before.save);results.push({case:'read-tab-pauses-without-world-change',game,state:await state()});}
 for(const game of ['workshop','shift','courier','courtyard','commons','commons-next','watch','signals','service','service-plan'])for(const [width,height]of [[375,667],[390,844],[1280,800],[640,400]]){await fresh(game,width,height);const panels=[];for(let i=0;i<5;i++){await tab(i);const data=await page.locator('[role=tabpanel]:not([hidden])').evaluate(p=>({width:p.clientWidth,scrollWidth:p.scrollWidth,height:p.clientHeight,scrollHeight:p.scrollHeight}));assert(data.scrollWidth<=data.width+1,`${game} ${width}: panel ${i} horizontal scroll ${JSON.stringify(data)}`);panels.push(data);}assert.equal((await state()).docWidth,width);results.push({case:'final-panel-overflow',game,width,height,panels});}
 for(const game of ['signals','service-plan']){await fresh(game);await page.locator('#play').click();await page.goto(origin+'/games/');await page.goBack();assert.equal((await state()).play,'false');const before=await state();await page.waitForTimeout(1200);assert.equal((await state()).clock,before.clock);results.push({case:'actual-leave-return-pauses',game,state:await state()});}
 await fresh('games',1280,800);assert.equal(await page.getByRole('tablist').getAttribute('aria-orientation'),'vertical');await page.getByRole('tab').first().focus();await page.keyboard.press('End');assert.equal(await page.getByRole('tab').last().getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowUp');assert.equal(await page.getByRole('tab').nth(8).getAttribute('aria-selected'),'true');results.push({case:'collection-vertical-keyboard-passes'});
 results.push({allPassed:true});
}catch(e){results.push({fatal:e.stack});process.exitCode=1;}finally{await writeFile(root+'/recheck-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results.map(({state,...r})=>({...r,state:state?{...state,save:'omitted from console only'}:undefined})),null,2));await browser.close();await new Promise(r=>server.close(r));}
