import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
import * as story from '/Users/abdul/code/human-framework/src/games/camp-story.js';
import * as slots from '/Users/abdul/code/human-framework/web/camp-slots.js';
import {chooseCommand} from '/Users/abdul/code/human-framework/src/games/commons-policy.js';
const dir='/tmp/camp-ui-review',url='http://127.0.0.1:4189',out=[];
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const key=slots.STORAGE_KEY;
async function setup(g=null,raw=null){const context=await browser.newContext({viewport:{width:375,height:667},acceptDownloads:true}),page=await context.newPage();await page.goto(url+'/games/');if(g||raw!==null){await page.evaluate(([key,raw])=>localStorage.setItem(key,raw),[key,raw??slots.serializeBook(slots.addStory(slots.createBook(),g,{id:'initial',at:0}))]);}await page.goto(url+'/camp/');await page.locator('#player-job').waitFor();return {context,page};}
const raw=p=>p.evaluate(key=>localStorage.getItem(key),key);async function current(p){return slots.getActiveGame(slots.restoreBook(await raw(p)));}const view=async p=>story.getGameView(await current(p));
const click=async(p,s)=>{await p.locator(s).click();};const selected=p=>p.locator('[role=tab][aria-selected=true]').getAttribute('id');const focus=p=>p.evaluate(()=>document.activeElement.id||document.activeElement.tagName);const log=(test,data)=>out.push({test,...data});
try{
// Actual new camp workflow, driven only by public choices and button actions.
let {context,page}=await setup();const initial=await current(page);await click(page,'#next-event');const recovered=await current(page);assert.ok(recovered.world.clock.now>0&&recovered.world.clock.now<100);assert.ok(recovered.world.people.player.body.fatigue<initial.world.people.player.body.fatigue);log('available-recovery',{before:initial.world.clock.now,after:recovered.world.clock.now,fatigue:recovered.world.people.player.body.fatigue});
await page.locator('#tab-work').focus();await page.keyboard.press('ArrowRight');assert.equal(await focus(page),'tab-people');await page.keyboard.press('End');assert.equal(await focus(page),'tab-save');await page.keyboard.press('Home');assert.equal(await focus(page),'tab-work');
await click(page,'[data-job="build-shelter"]');await click(page,'#one-minute');let busy=await current(page);await page.reload();assert.deepEqual(await current(page),busy);assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');assert.ok((await page.locator('#player-timing').innerText()).includes('23'));log('refresh-active',{at:busy.world.clock.now,work:busy.world.work.shelter.progress});
await click(page,'#tab-people');await click(page,'#offer-work');log('handover-offer',{notice:await page.locator('#notice').innerText(),status:await page.locator('#time-status').innerText(),jobs:(await view(page)).people});await click(page,'#take-work');log('handover-take',{notice:await page.locator('#notice').innerText(),status:await page.locator('#time-status').innerText(),focus:await focus(page)});
await click(page,'#tab-journal');assert.equal(await page.locator('#stop').isVisible(),true);await click(page,'#stop');assert.ok(!(await view(page)).people.player.job);log('stop-persistent',{focus:await focus(page)});
for(let i=0;i<500&&(await view(page)).phase==='camp';i++){
 const v=await view(page),c=chooseCommand(v);
 if(c.type==='request'){await click(page,'#tab-people');await page.locator('#request-project').selectOption(c.projectId);await click(page,'#request');}
 else if(c.type==='start'&&c.jobId!=='rest'){if(c.jobId==='eat'){await click(page,'#tab-people');await click(page,'#eat');}else{await click(page,'#tab-work');if(c.jobId.startsWith('build-'))await page.locator('#project').selectOption(c.jobId.slice(6));await click(page,`[data-job="${c.jobId}"]`);}}
 else await click(page,'#next-event');
}
assert.equal((await view(page)).phase,'introduction');assert.equal(await selected(page),'tab-camp');assert.equal(await focus(page),'chapter-title');const intro=await current(page);await click(page,'#chapter-action');assert.equal((await view(page)).phase,'packing');assert.deepEqual((await current(page)).world,intro.world);log('continue-transition',{focus:await focus(page),selected:await selected(page),project:await page.locator('#project').inputValue()});
while((await view(page)).phase==='packing')await click(page,'#next-event');assert.equal(await selected(page),'tab-camp');assert.equal(await focus(page),'chapter-title');await page.locator('#chapter-action').focus();await page.keyboard.press('Enter');log('dispatch-transition',{focus:await focus(page),selected:await selected(page),phase:(await view(page)).phase});
while((await view(page)).phase==='packing')await click(page,'#next-event');assert.equal((await view(page)).phase,'rain');await click(page,'#chapter-action');assert.equal((await view(page)).phase,'ended');assert.equal(await focus(page),'result-title');const end=await current(page);await click(page,'#return-camp');assert.deepEqual((await current(page)).world,end.world);await click(page,'#next-event');assert.ok((await view(page)).now>end.world.clock.now);log('return-transition',{focus:await focus(page),selected:await selected(page),now:(await view(page)).now});await context.close();
// Book with five UI-created independent stories; one active job and one import.
({context,page}=await setup());await click(page,'[data-job="gather-timber"]');await click(page,'#one-minute');const camp1=await current(page);await click(page,'#tab-save');const dl=page.waitForEvent('download');await click(page,'#download');const download=await dl;await download.saveAs(dir+'/download.json');assert.deepEqual(JSON.parse(fs.readFileSync(dir+'/download.json','utf8')),story.exportGame(camp1));
for(let i=0;i<3;i++){await page.getByText('Start a separate story',{exact:true}).click();await click(page,'#new-story');await click(page,'#one-minute');await click(page,'#tab-save');}
await page.locator('#import').setInputFiles(dir+'/download.json');assert.equal(await page.locator('#import-preview').isVisible(),true);await click(page,'#confirm-import');await click(page,'#tab-save');let book=slots.restoreBook(await raw(page));assert.equal(book.slots.length,5);assert.deepEqual(slots.getActiveGame(book),camp1);assert.equal(await page.locator('#new-story').isDisabled(),true);await page.screenshot({path:dir+'/375-five-slots.png'});
let saved=await raw(page);page.once('dialog',dialog=>dialog.dismiss());await page.locator('[data-remove]').first().click();assert.equal(await raw(page),saved);page.once('dialog',dialog=>dialog.accept());await page.locator('[data-remove]').last().click();book=slots.restoreBook(await raw(page));assert.equal(book.slots.length,4);assert.deepEqual(slots.getActiveGame(book),camp1);await click(page,'#tab-save');await page.locator('[data-slot]').nth(1).click();await click(page,'#tab-save');await page.locator('[data-slot]').first().click();assert.deepEqual(await current(page),camp1);log('five-slots',{countBefore:5,countAfter:4,importIsExact:true,deleteCancelNoWrite:true,isolatedStory:true});await context.close();
// Corrupt inactive save remains protected; own synthetic raw only.
const corrupt='{ "format": "broken-review" }';({context,page}=await setup(null,corrupt));assert.equal(await raw(page),corrupt);assert.equal(await page.locator('#save-warning').isVisible(),true);await click(page,'[data-job="gather-timber"]');await click(page,'#one-minute');assert.equal(await raw(page),corrupt);await click(page,'#tab-save');const backupWait=page.waitForEvent('download');await page.getByRole('button',{name:'Download the stored-data backup'}).click();const backup=await backupWait;await backup.saveAs(dir+'/backup.json');assert.equal(fs.readFileSync(dir+'/backup.json','utf8'),corrupt);log('corruption',{rawProtected:true,backupExact:true,warning:await page.locator('#save-warning').innerText()});await context.close();
// Force a quota error after a valid initial save; active work must remain downloadable.
({context,page}=await setup());const preQuota=await raw(page);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('review quota','QuotaExceededError');};});await click(page,'[data-job="gather-timber"]');await click(page,'#one-minute');assert.equal(await raw(page),preQuota);assert.equal(await page.locator('#save-warning').isVisible(),true);await click(page,'#tab-save');const qw=page.waitForEvent('download');await click(page,'#download');const qd=await qw;await qd.saveAs(dir+'/quota.json');const qg=story.restoreGame(JSON.parse(fs.readFileSync(dir+'/quota.json','utf8')));assert.equal(qg.world.clock.now,1);assert.equal(qg.world.people.player.pending.elapsedMinutes,1);log('quota',{retainedInMemory:true,downloadPendingMinutes:qg.world.people.player.pending.elapsedMinutes,warning:await page.locator('#save-warning').innerText()});await context.close();
}catch(e){out.push({failure:e.message,stack:e.stack});process.exitCode=1;}
await browser.close();fs.writeFileSync(dir+'/interactions.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
