import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import * as camp from '/Users/abdul/code/human-framework/src/games/camp-current.js';
import {readFile,writeFile,appendFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const root=process.cwd(),dir=process.env.UI_OUTPUT,url=process.env.UI_BASE,key='human-camp-current-v0.3.0',states=JSON.parse(await readFile(dir+'/synthetic-states.json','utf8')),out={sources:[],observations:[],errors:[],network:[]},hash=x=>createHash('sha256').update(x).digest('hex');
for(const file of ['web/camp-current.js','web/camp-current-session.js','web/camp.html','web/camp.css','web/game-shell.css','src/games/camp-current.js']){const response=await fetch(url+(file==='web/camp.html'?'/camp/':'/'+file));assert.equal(response.status,200);const served=hash(Buffer.from(await response.arrayBuffer())),local=hash(await readFile(root+'/'+file));assert.equal(served,local);out.sources.push({file,sha256:served});}assert.equal(out.sources.find(s=>s.file==='web/camp-current.js').sha256,'9bba1d23e43b65ea25a6a1f7810d84a47cb394e291d2007685417e3ac1c97c47');
const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:375,height:667}});await ctx.route('**/*',r=>{const u=r.request().url();if(u.startsWith(url))return r.continue();out.network.push(u);return r.abort();});const p=await ctx.newPage();p.on('pageerror',e=>out.errors.push(e.message));p.on('console',m=>{if(['warning','error'].includes(m.type()))out.errors.push(m.text());});
async function load(s){await p.goto(url+'/camp/');await p.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key,s});await p.reload();await p.locator('[data-job]').first().waitFor({state:'attached'});}
await load(states.ferry);const expected=camp.getGameView(camp.restoreGame(states.ferry)).pauseReason,actual=await p.locator('#time-status').innerText();assert.equal(actual,expected);out.observations.push({case:'restored ferry checkpoint status',pass:true,actual});await p.screenshot({path:dir+'/corrective-ferry-status.png'});
await p.locator('#tab-save').click();await p.locator('#import').setInputFiles({name:'ferry-current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(states.ferry))});await p.locator('#confirm-import').click();assert.equal(await p.locator('#time-status').innerText(),expected);out.observations.push({case:'imported ferry checkpoint status',pass:true,actual:await p.locator('#time-status').innerText()});
await load(states.ended);await p.locator('#return-camp').click();const hint=await p.locator('#work-hint').innerText();assert.match(hint,/stored|storage/);assert.match(hint,/settled/);assert.doesNotMatch(hint,/serve one household|covers? two/);out.observations.push({case:'returned camp cache hint',pass:true,actual:hint});await p.screenshot({path:dir+'/corrective-returned-cache-hint.png'});
await p.locator('[data-job="build-cache"]').click();await p.locator('#one-minute').click();await p.locator('#stop').click();const detail=await p.locator('[data-job="build-cache"] .choice-detail').innerText();assert.equal(detail,'Pack timber and salvage into one supply cache.');out.observations.push({case:'stopped partially paid returned-cache card',pass:true,actual:detail,hint:await p.locator('#work-hint').innerText()});await p.screenshot({path:dir+'/corrective-resumed-cache-card.png'});
assert.deepEqual(out.errors,[]);assert.deepEqual(out.network,[]);for(const item of out.sources)assert.equal(hash(await readFile(root+'/'+item.file)),item.sha256,'source changed during narrow recheck '+item.file);await browser.close();await writeFile(dir+'/corrective-results.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
