import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import * as camp from '/Users/abdul/code/human-framework/src/games/camp-current.js';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const dir=process.env.UI_OUTPUT,root=process.cwd(),url=process.env.UI_BASE,key='human-camp-current-v0.3.0',oldKey='human-camp-story-v0.1.0';
assert(dir&&url,'UI_OUTPUT and UI_BASE required'); await mkdir(dir,{recursive:false});
const results=[],errors=[],network=[],hash=x=>createHash('sha256').update(x).digest('hex');
for(const [route,path] of [['/camp/','web/camp.html'],...['web/camp-current.js','web/camp-current-session.js','web/camp.css','web/game-shell.css','src/games/camp-current.js'].map(p=>['/'+p,p])]){const res=await fetch(url+route);assert.equal(res.status,200);const bytes=Buffer.from(await res.arrayBuffer());assert.equal(hash(bytes),hash(await readFile(root+'/'+path)));results.push({probe:'served source',route,sha256:hash(bytes)});}
let game=camp.createGame();
function run(job){for(let i=0;i<200;i++){const v=camp.getGameView(game),c=v.choices.find(c=>c.id===job);assert(c,'job exists '+job);if(!c.unavailable){game=camp.applyCommand(game,{type:'start',job});while(camp.getGameView(game).people.player.job&&camp.getGameView(game).canAdvance)game=camp.advanceToNextEvent(game);return;}const missing=Object.entries(c.cost).find(([r,n])=>v.stock[r]<n);if(missing){run({timber:'gather-timber',salvage:'gather-salvage',food:'forage'}[missing[0]]);continue;}const eat=v.choices.find(c=>c.id==='eat');if(v.people.player.body.hunger>.4&&!eat.unavailable){run('eat');continue;}game=camp.advanceGame(game,15);}throw Error('cannot run '+job);}
for(const p of ['shelter','workbench'])for(let i=0;i<2;i++)run('build-'+p);
for(const [res,need,job]of [['timber',38,'gather-timber'],['salvage',20,'gather-salvage'],['food',10,'forage']])while(camp.getGameView(game).stock[res]<need)run(job);
for(let i=0;i<2;i++)run('build-garden');
const intro=camp.exportGame(game);assert.equal(camp.getGameView(game).phase,'introduction');
game=camp.applyCommand(game,{type:'continue'});
for(let i=0;i<2;i++)run('build-cache');
const packing=camp.exportGame(game);
while(camp.getGameView(game).phase!=='ferry')game=camp.advanceGame(game,15);
const ferry=camp.exportGame(game);
game=camp.applyCommand(game,{type:'dispatch'});while(camp.getGameView(game).phase!=='rain')game=camp.advanceGame(game,30);
const rain=camp.exportGame(game);game=camp.applyCommand(game,{type:'finish'});const ended=camp.exportGame(game);
await writeFile(dir+'/synthetic-states.json',JSON.stringify({intro,packing,ferry,rain,ended},null,2));
const browser=await chromium.launch({channel:'chrome',headless:true});
const ctx=await browser.newContext({viewport:{width:375,height:667},acceptDownloads:true});
await ctx.route('**/*',async route=>{const u=route.request().url();if(u.startsWith(url)||u.startsWith('data:')||u.startsWith('blob:'))await route.continue();else{network.push(u);await route.abort();}});
await ctx.addInitScript(({key,oldKey})=>{window.__storageCalls=[];const get=Storage.prototype.getItem,set=Storage.prototype.setItem,remove=Storage.prototype.removeItem;Storage.prototype.getItem=function(k){window.__storageCalls.push(['get',k]);return get.call(this,k)};Storage.prototype.setItem=function(k,v){window.__storageCalls.push(['set',k]);return set.call(this,k,v)};Storage.prototype.removeItem=function(k){window.__storageCalls.push(['remove',k]);return remove.call(this,k)};window.__realGet=get;window.__realSet=set;window.__realRemove=remove;},{key,oldKey});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.type()+': '+m.text())});page.on('dialog',async d=>{results.push({probe:'dialog',type:d.type(),message:d.message()});await d.accept();});
async function probe(name,fn){try{const detail=await fn();results.push({probe:name,pass:true,detail});}catch(e){results.push({probe:name,pass:false,error:e.stack});}await writeFile(dir+'/results.json',JSON.stringify({results,errors,network},null,2));}
async function state(){return JSON.parse(await page.evaluate(k=>window.__realGet.call(localStorage,k),key));}
async function load(s){await page.goto(url+'/camp/');await page.evaluate(({key,oldKey,s})=>{window.__realSet.call(localStorage,oldKey,'old-key-canary-unread');if(s===null)window.__realRemove.call(localStorage,key);else window.__realSet.call(localStorage,key,typeof s==='string'?s:JSON.stringify(s));},{key,oldKey,s});await page.reload();await page.locator('[data-job]').first().waitFor({state:'attached'});}
async function geometry(){return page.evaluate(()=>{const r=document.querySelector('.game-dock').getBoundingClientRect();const panel=document.querySelector('.game-panel:not([hidden])');return {width:innerWidth,height:innerHeight,docWidth:document.documentElement.scrollWidth,docHeight:document.documentElement.scrollHeight,dock:{x:r.x,y:r.y,bottom:r.bottom},panel:{height:panel.clientHeight,scrollHeight:panel.scrollHeight,scrollWidth:panel.scrollWidth,clientWidth:panel.clientWidth},focus:document.activeElement.id};});}
async function checkLayout(name){const g=await geometry();assert(g.docWidth<=g.width,'horizontal page overflow');assert(g.panel.scrollWidth<=g.panel.clientWidth+1,'horizontal panel overflow');if(g.height>570){assert(g.dock.bottom<=g.height+1,'dock clipped');assert(g.panel.height>50,'panel too short');}await page.screenshot({path:dir+'/'+name+'.png'});return g;}
await probe('phone fresh all tabs layout and keyboard',async()=>{await load(null);const layouts={};for(const tab of ['work','people','camp','journal','save']){await page.locator('#tab-'+tab).click();layouts[tab]=await checkLayout('phone-'+tab);}await page.locator('#tab-work').focus();await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-save');await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-work');await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-save');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-work');return layouts;});
await probe('paid start pause tab stop reload and old-key isolation',async()=>{await page.locator('[data-job="build-shelter"]').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'next-event');await page.locator('#one-minute').click();let s=await state();assert.equal(s.game.clock.now,1);assert(s.game.work.shelter.progress>0);await page.locator('#play').click();await page.locator('#tab-people').click();assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');const before=await state();await page.waitForTimeout(1200);assert.deepEqual(await state(),before);await page.locator('#stop').click();const stopped=await state();assert.equal(stopped.game.jobs.player,null);assert.equal(stopped.game.work.shelter.progress,before.game.work.shelter.progress);await page.reload();assert.deepEqual(await state(),stopped);assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');const calls=await page.evaluate(()=>window.__storageCalls);assert(calls.every(x=>x[1]===key));assert.equal(await page.evaluate(k=>window.__realGet.call(localStorage,k),oldKey),'old-key-canary-unread');return {minute:stopped.game.clock.now,retained:stopped.game.work.shelter.progress,calls};});
await probe('actual current download import cancel confirm and unsupported old format',async()=>{await page.locator('#tab-save').click();const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;await download.saveAs(dir+'/current-download.json');const saved=JSON.parse(await readFile(dir+'/current-download.json','utf8'));camp.restoreGame(saved);await page.locator('#import').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'human-camp-story',version:1}))});await page.locator('#notice').waitFor({state:'visible'});assert.match(await page.locator('#notice').innerText(),/Earlier camp formats are unsupported/);assert.deepEqual(await state(),saved);await page.locator('#import').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packing))});await page.locator('#import-preview').waitFor({state:'visible'});assert.match(await page.locator('#import-detail').innerText(),new RegExp('Camp minute '+packing.game.clock.now));assert.deepEqual(await state(),saved);await page.locator('#cancel-import').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'import');assert.deepEqual(await state(),saved);await page.locator('#import').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packing))});await page.locator('#confirm-import').click();assert.deepEqual(await state(),packing);await page.reload();assert.deepEqual(await state(),packing);return {filename:download.suggestedFilename(),minute:packing.game.clock.now};});
await probe('import preview invalidated by advancement and delayed stale success/failure',async()=>{await page.locator('#tab-save').click();await page.locator('#import').setInputFiles({name:'new.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(intro))});await page.locator('#import-preview').waitFor({state:'visible'});await page.locator('#one-minute').click();assert(await page.locator('#import-preview').isHidden());const changed=await state();await page.evaluate(()=>{window.__fileText=File.prototype.text;File.prototype.text=function(){return new Promise((resolve,reject)=>{window.__resolveFile=()=>window.__fileText.call(this).then(resolve,reject);window.__rejectFile=()=>reject(new Error('late failure'));});};});await page.locator('#import').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(intro))});await page.locator('#one-minute').click();const newer=await state();await page.evaluate(()=>window.__resolveFile());await page.waitForTimeout(100);assert(await page.locator('#import-preview').isHidden());assert.deepEqual(await state(),newer);await page.locator('#import').setInputFiles({name:'slow-bad.json',mimeType:'application/json',buffer:Buffer.from('bad')});await page.locator('#one-minute').click();await page.evaluate(()=>window.__rejectFile());await page.waitForTimeout(100);assert(!await page.locator('#notice').isVisible());await page.evaluate(()=>File.prototype.text=window.__fileText);return {original:changed.game.clock.now,newer:newer.game.clock.now};});
await probe('phone introduction checkpoint continue and ferry allocation dispatch',async()=>{await load(intro);assert.equal(await page.locator('#tab-camp').getAttribute('aria-selected'),'true');const introLayout=await checkLayout('phone-introduction');assert(await page.locator('#next-event').isHidden());await page.locator('#chapter-action').click();assert.equal((await state()).game.clock.now,intro.game.clock.now);assert.equal(camp.getGameView(camp.restoreGame(await state())).phase,'packing');await load(ferry);const ferryLayout=await checkLayout('phone-ferry');await page.locator('#allocate-households').click();assert.equal(await page.locator('#household-count').innerText(),'1 / 2 kits');await page.locator('#allocate-camp').click();assert.equal(await page.locator('#camp-count').innerText(),'2 / 4 nights');const allocated=await state();assert.equal(camp.getGameView(camp.restoreGame(allocated)).availableCaches,0);await page.locator('#chapter-action').click();const dispatched=await state();assert.equal(dispatched.game.clock.now,allocated.game.clock.now);assert.equal(dispatched.game.window.departedAt,allocated.game.clock.now);return {introLayout,ferryLayout,allocations:allocated.game.window.allocations};});
await probe('rain close return preserves people work supply account',async()=>{await load(rain);const layout=await checkLayout('phone-rain');await page.locator('#allocate-camp').click();const before=await state();await page.locator('#chapter-action').click();assert.equal(camp.getGameView(camp.restoreGame(await state())).phase,'ended');await checkLayout('phone-ended');await page.locator('#return-camp').click();const after=await state();assert.equal(camp.getGameView(camp.restoreGame(after)).phase,'camp-return');assert.equal(after.game.clock.now,before.game.clock.now);assert.deepEqual(after.game.people,before.game.people);assert.deepEqual(after.game.work,before.game.work);assert.deepEqual(after.game.window.allocations,before.game.window.allocations);return layout;});
await probe('quota failure Save and leave keeps current downloadable',async()=>{await load(ended);await page.evaluate(()=>{window.__priorSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')};});await page.locator('#save-leave').click();assert.equal(page.url(),url+'/camp/');assert.equal(await page.locator('#tab-save').getAttribute('aria-selected'),'true');assert(await page.locator('#save-warning').isVisible());await checkLayout('phone-quota');const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;await download.saveAs(dir+'/quota-download.json');assert.deepEqual(JSON.parse(await readFile(dir+'/quota-download.json','utf8')),ended);await page.evaluate(()=>Storage.prototype.setItem=window.__priorSet);return {minute:ended.game.clock.now,warning:await page.locator('#save-warning').innerText()};});
await probe('corruption remains protected through play new camp import and raw backup download',async()=>{await load('{broken current');assert(await page.locator('#save-warning').isVisible());await page.locator('[data-job="build-shelter"]').click();await page.locator('#one-minute').click();assert.equal(await page.evaluate(k=>window.__realGet.call(localStorage,k),key),'{broken current');await page.locator('#tab-save').click();let promise=page.waitForEvent('download');await page.getByRole('button',{name:'Download unreadable device save'}).click();let d=await promise;await d.saveAs(dir+'/corrupt-backup.json');assert.equal(await readFile(dir+'/corrupt-backup.json','utf8'),'{broken current');await page.getByText('Start a new camp',{exact:true}).click();await page.locator('#new-camp').click();assert.equal(await page.evaluate(k=>window.__realGet.call(localStorage,k),key),'{broken current');await page.locator('#tab-save').click();await page.locator('#import').setInputFiles({name:'new.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packing))});await page.locator('#confirm-import').click();assert.equal(await page.evaluate(k=>window.__realGet.call(localStorage,k),key),'{broken current');return await checkLayout('phone-protected-save');});
await probe('desktop and short-height expanded content keyboard dock accessibility',async()=>{await page.setViewportSize({width:1280,height:900});await load(packing);await page.locator('#tab-people').click();await checkLayout('desktop-people');await page.locator('#tab-work').click();await checkLayout('desktop-work');await page.setViewportSize({width:375,height:500});await page.locator('#tab-save').click();await page.getByText('Model notes',{exact:true}).click();await page.getByText('Start a new camp',{exact:true}).click();await page.locator('#play').focus();const dock=await page.locator('.game-dock').boundingBox();assert(dock.y+dock.height<=501);return await checkLayout('short-expanded-save');});
await probe('no browser warnings errors or external network',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(network,[]);return {errors,network};});
await browser.close();await writeFile(dir+'/results.json',JSON.stringify({results,errors,network},null,2));console.log(JSON.stringify(results.filter(r=>r.pass!==undefined),null,2));

assert(results.filter(r=>r.pass!==undefined).length===10);assert(results.every(r=>r.pass!==false),'browser probe failed');assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
