import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import * as camp from '/Users/abdul/code/human-framework/src/games/camp-current.js';
import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const dir='/tmp/camp-current-ui-review',url='http://127.0.0.1:4187',key='human-camp-current-v0.3.0',states=JSON.parse(await readFile(dir+'/synthetic-states.json','utf8')),out=[];
const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:375,height:667}});await ctx.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());const p=await ctx.newPage();p.on('dialog',d=>d.accept());
async function load(s){await p.goto(url+'/camp/');await p.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key,s});await p.reload();await p.locator('[data-job]').first().waitFor({state:'attached'});}
async function current(){return JSON.parse(await p.evaluate(k=>localStorage.getItem(k),key));}
async function importState(s,name='current.json'){await p.locator('#import').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});}
await load(states.ferry);out.push({probe:'restored checkpoint status',expected:camp.getGameView(camp.restoreGame(states.ferry)).pauseReason,actual:await p.locator('#time-status').innerText(),phase:'ferry'});await p.screenshot({path:dir+'/finding-restored-ferry-status.png'});
await load(states.ended);await p.locator('#return-camp').click();out.push({probe:'returned camp cache benefit',phase:camp.getGameView(camp.restoreGame(await current())).phase,hint:await p.locator('#work-hint').innerText(),objective:await p.locator('#objective').innerText()});await p.screenshot({path:dir+'/finding-returned-cache-hint.png'});await p.locator('#tab-camp').click();out.at(-1).allocationSectionHidden=await p.locator('#supplies').isHidden();out.at(-1).result=await p.locator('#result-detail').innerText();
await load(camp.exportGame(camp.createGame()));await p.locator('#tab-people').click();await p.locator('#tab-people').focus();const ids=[];for(let i=0;i<10;i++){await p.keyboard.press('Tab');ids.push(await p.evaluate(()=>document.activeElement.id||document.activeElement.textContent.trim().slice(0,40)));if(ids.at(-1)==='request')break;}assert(ids.includes('request'));const r=await p.locator('#request').boundingBox(),panel=await p.locator('#panel-people').boundingBox();assert(r.y>=panel.y&&r.y+r.height<=panel.y+panel.height+1);await p.keyboard.press('Enter');assert.match(await p.locator('#commitment-status').innerText(),/Project accepted/);out.push({probe:'keyboard Meryem request scroll and submit',pass:true,tabSequence:ids});
await p.locator('#tab-save').click();await p.evaluate(()=>{window.__origText=File.prototype.text;window.__pending=[];File.prototype.text=function(){return new Promise((resolve,reject)=>{window.__pending.push(()=>window.__origText.call(this).then(resolve,reject));});};});await importState(states.intro,'slow-first.json');await importState(states.packing,'slow-second.json');await p.evaluate(()=>window.__pending[1]());await p.locator('#import-preview').waitFor({state:'visible'});const expectedDetail=await p.locator('#import-detail').innerText();await p.evaluate(()=>window.__pending[0]());await p.waitForTimeout(100);assert.equal(await p.locator('#import-detail').innerText(),expectedDetail);await p.locator('#confirm-import').click();assert.deepEqual(await current(),states.packing);out.push({probe:'newer read wins over delayed earlier success',pass:true,adoptedMinute:states.packing.game.clock.now});
await p.locator('#tab-save').click();await importState(states.intro,'newcamp-stale.json');await p.getByText('Start a new camp',{exact:true}).click();await p.locator('#new-camp').click();await p.evaluate(()=>window.__pending[2]());await p.waitForTimeout(100);assert(await p.locator('#import-preview').isHidden());assert.equal((await current()).game.clock.now,0);out.push({probe:'new camp invalidates a delayed import',pass:true});
const denied=await browser.newContext({viewport:{width:375,height:667}});await denied.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await denied.addInitScript(({key})=>{window.__deniedWrites=[];const get=Storage.prototype.getItem,set=Storage.prototype.setItem;Storage.prototype.getItem=function(k){if(k===key)throw new DOMException('Denied','SecurityError');return get.call(this,k);};Storage.prototype.setItem=function(k,v){window.__deniedWrites.push(k);return set.call(this,k,v);};},{key});const q=await denied.newPage();await q.goto(url+'/camp/');await q.locator('[data-job="build-shelter"]').click();await q.locator('#one-minute').click();assert(await q.locator('#save-warning').isVisible());assert.deepEqual(await q.evaluate(()=>window.__deniedWrites),[]);out.push({probe:'read-denied storage never overwritten through play',pass:true,warning:await q.locator('#save-warning').innerText()});
await writeFile(dir+'/followup-results.json',JSON.stringify(out,null,2));await browser.close();console.log(JSON.stringify(out,null,2));
