import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
const base=process.argv[2]??'http://127.0.0.1:4192',label=process.argv[3]??'local',out='/tmp/hf-release-06-'+label;
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
const errors=[],failedRequests=[],prefetchRefusals=[],networkChecks=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)networkChecks.push((async()=>{
 const headers=await r.allHeaders(),requestHeaders=await r.request().allHeaders();
 const item={url:r.url(),status:r.status(),resource:r.request().resourceType(),navigation:r.request().isNavigationRequest(),purpose:requestHeaders['sec-purpose']??null,refusal:headers['cf-speculation-refused']??null};
 const prefetch=item.status===503&&!item.navigation&&item.resource==='other'&&/prefetch/i.test(item.purpose??'')&&item.refusal==='prefetch refused: disabled for worker requests';
 (prefetch?prefetchRefusals:failedRequests).push(item);
})());});
const rainKey='human-common-ground-before-rain-v1',watchKey='human-before-the-water-v1';
const saved=key=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
const rain=()=>saved(rainKey),watch=()=>saved(watchKey);
const importJSON=async obj=>{await page.locator('#load').setInputFiles({name:'qa-save.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(obj))});};
const restartRain=async()=>{if(!await page.locator('#new-run').isVisible())await page.getByText('Start another afternoon',{exact:true}).click();await page.locator('#new-run').click();};
const restartWatch=async scenario=>{if(!await page.locator('#restart').isVisible())await page.getByText('Start a new episode',{exact:true}).click();await page.locator('#scenario').selectOption(scenario);await page.locator('#restart').click();};
const noOverflow=async scope=>{for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,scope+' overflow '+width);}};
try{
 await page.goto(base+'/games/');assert.equal(await page.locator('a.game').count(),7);assert.equal(await page.locator('details[open]').count(),0);await noOverflow('gallery');await page.screenshot({path:out+'/games-1280.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('a.game[href="/commons-next/"]').click();await page.locator('#opening-actions button').first().waitFor();
 assert.equal(await page.locator('details[open]').count(),0);const first=await page.locator('#opening-actions button').first().boundingBox();assert.ok(first.y+first.height<844,'rain first real action visible');
 assert.doesNotMatch(await page.locator('#commitment-status').innerText(),/^Cache complete$/);assert.equal(await page.locator('#response').isVisible(),false);await page.screenshot({path:out+'/rain-opening-390.png',fullPage:true});
 await page.locator('#opening-actions [data-job="gather-timber"]').focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Ask Meryem for a cache',exact:true}).click();
 let r=await rain();assert.ok(r.game.world.jobs.player&&r.game.world.jobs.neighbor);await page.locator('#next-event').click();r=await rain();assert.equal(r.game.world.clock.now-r.game.openedAt,15);const manual=JSON.stringify(r);
 const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const downloaded=await downloadPromise;const downloadPath=await downloaded.path();assert.match(downloaded.suggestedFilename(),/before-rain/);
 await restartRain();await page.locator('#load').setInputFiles(downloadPath);await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).game.world.clock.now-JSON.parse(localStorage.getItem(k)).game.openedAt===15,rainKey);assert.equal(JSON.stringify(await rain()),manual);
 await importJSON({format:'wrong'});await page.getByText(/Save was not loaded/).waitFor();assert.equal(JSON.stringify(await rain()),manual);await page.reload();assert.match(await page.locator('#time-status').innerText(),/Paused/);assert.equal(JSON.stringify(await rain()),manual);
 await restartRain();await page.locator('#opening-actions [data-job="gather-timber"]').click();await page.getByRole('button',{name:'Ask Meryem for a cache',exact:true}).click();await page.locator('#speed').selectOption('4');await page.locator('#play').click();
 await page.waitForFunction(k=>{const x=JSON.parse(localStorage.getItem(k));return x.game.world.clock.now-x.game.openedAt>=15;},rainKey,{timeout:12000});assert.equal(JSON.stringify(await rain()),manual);assert.match(await page.locator('#time-status').innerText(),/Paused/);
 checks.push('Rain: visible keyboard-operable first action; simultaneous work; actual download/import; invalid save preservation; paused reload; real 4x playback matches event step exactly');
 await restartRain();await page.locator('#opening-actions [data-job="gather-salvage"]').click();await page.getByRole('button',{name:'Ask Meryem for a cache',exact:true}).click();
 const rainAt=async()=>{const x=await rain();return x.game.world.clock.now-x.game.openedAt;};
 for(const minute of [15,21]){await page.locator('#next-event').click();assert.equal(await rainAt(),minute);}
 await page.locator('#build-choices [data-job="build-cache"]').click();
 for(const minute of [36,40]){await page.locator('#next-event').click();assert.equal(await rainAt(),minute);}
 await page.locator('#request').click();await page.locator('#gather-choices [data-job="rest"]').click();await page.locator('#next-event').click();assert.equal(await rainAt(),54);
 await page.locator('#cancel').click();await page.locator('#gather-choices [data-job="gather-timber"]').click();await page.locator('#next-event').click();assert.equal(await rainAt(),69);
 await page.locator('#gather-choices [data-job="rest"]').click();
 for(const minute of [87,88,90]){await page.locator('#next-event').click();assert.equal(await rainAt(),minute);}
 assert.equal((await rain()).game.world.caches,2);await page.locator('#allocate-households').click();await page.locator('#allocate-households').click();assert.match(await page.locator('#households').innerText(),/2 \/ 2/);
 checks.push('Rain: full two-cache schedule through visible buttons and next-event boundaries, including14 paid rest minutes and two households equipped before ferry90');
 const fixture=await page.evaluate(async()=>{const n=await import('/src/games/commons-next.js'),o=await import('/src/games/commons.js'),p=await import('/src/games/commons-policy.js');let g=n.createGame();for(let i=0;i<300&&n.getGameView(g).phase==='packing';i++){const c=p.chooseCommand(o.getGameView(g.world));g=c.type==='start'?n.startJob(g,c.jobId):c.type==='request'?n.requestProject(g,c.projectId):n.advanceToNextEvent(g);}return n.exportGame(g);});
 await importJSON(fixture);await page.getByRole('heading',{name:'The ferry is ready to leave.'}).waitFor();assert.equal(await page.locator('#next-event').isDisabled(),true);await page.locator('#allocate-households').click();assert.equal((await rain()).game.allocations.length,1);await page.locator('#continue').click();assert.equal(await page.locator('#allocate-households').isDisabled(),true);
 const dusk=await page.evaluate(async()=>{const n=await import('/src/games/commons-next.js'),o=await import('/src/games/commons.js'),p=await import('/src/games/commons-policy.js');let g=n.restoreGame(JSON.parse(localStorage.getItem('human-common-ground-before-rain-v1')));for(let i=0;i<300&&n.getGameView(g).phase==='packing';i++){const c=p.chooseCommand(o.getGameView(g.world));g=c.type==='start'?n.startJob(g,c.jobId):c.type==='request'?n.requestProject(g,c.projectId):n.advanceToNextEvent(g);}return n.exportGame(g);});
 await importJSON(dusk);await page.getByRole('heading',{name:'The rain is here. Take stock.'}).waitFor();await page.locator('#allocate-camp').click();await page.locator('#allocate-camp').click();await page.locator('#continue').click();assert.equal((await rain()).game.ended,true);assert.match(await page.locator('#result-detail').innerText(),/1 of 2 households.*4 of 4 wet nights/);await noOverflow('rain');await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/rain-result-390.png',fullPage:true});
 checks.push('Rain: valid generated ferry/dusk fixtures exercise actual allocation, irreversible departure, paused checkpoints, bounded ending and result UI');
 const rainPreserved=JSON.stringify(await rain());await page.goto(base+'/commons/');await page.locator('#opening-jobs').waitFor();assert.equal(await page.locator('details[open]').count(),0);assert.equal(JSON.stringify(await rain()),rainPreserved);checks.push('Original ongoing Common Ground remains available and uses separate save state');
 await page.goto(base+'/watch/');await page.locator('#keeper-repair').waitFor();assert.equal(await page.locator('details[open]').count(),0);await page.screenshot({path:out+'/watch-opening-390.png',fullPage:true});
 // An explicit refusal does not consume time or resources.
 await page.locator('#watcher-share').click();assert.match(await page.locator('#watcher-response').innerText(),/keeping my spare/);let w=await watch();assert.equal(w.state.clock.now,0);assert.deepEqual(w.state.parts,{keeper:2,watcher:1});
 await page.locator('#keeper-bypass').click();await page.locator('#watcher-watch').click();await page.locator('#one-minute').click();await page.locator('#one-minute').click();await page.locator('#one-minute').click();w=await watch();assert.equal(w.state.clock.now,3);const mid=JSON.stringify(w);
 const watchDownload=page.waitForEvent('download');await page.locator('#download').click();const dw=await watchDownload;const watchPath=await dw.path();assert.match(dw.suggestedFilename(),/before-the-water-minute-3/);
 await page.reload();assert.equal(JSON.stringify(await watch()),mid);assert.match(await page.locator('#time-status').innerText(),/Paused/);await importJSON({format:'wrong'});await page.getByText(/Save was not loaded/).waitFor();assert.equal(JSON.stringify(await watch()),mid);
 await page.locator('#load').setInputFiles(watchPath);await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,6);await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,10);await page.locator('#watcher-open').click();await page.locator('#speed').selectOption('4');await page.locator('#play').click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).state.clock.now>=14,watchKey,{timeout:10000});assert.equal((await watch()).state.clock.now,14);assert.match(await page.locator('#time-status').innerText(),/Time paused/);await page.locator('#next-event').click();w=await watch();assert.equal(w.state.outcome.protected,true);assert.equal(w.state.outcome.waterService,false);assert.equal(await page.locator('#play').isDisabled(),true);
 checks.push('Watch: refusal preserves resources/time; partial owned work; actual save download/import; invalid file and reload preservation; exact playback pause; completed diversion with service closed');
 // Full short-notice success from buttons, including deliberately interrupted recovery.
 await restartWatch('short');await page.locator('#keeper-repair').click();await page.locator('#watcher-watch').click();await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,6);await page.locator('#keeper-repair').click();await page.locator('#watcher-share').click();await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,8);await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,12);
 const more=page.locator('#keeper-more').locator('..');if(!await page.locator('#keeper-rest').isVisible())await more.locator('summary').click();await page.locator('#keeper-rest').click();for(let i=0;i<3;i++)await page.locator('#one-minute').click();assert.equal((await watch()).state.clock.now,15);await page.locator('#keeper-stop').click();await page.locator('#keeper-repair').click();await page.locator('#next-event').click();assert.equal((await watch()).state.clock.now,21);await page.locator('#next-event').click();w=await watch();assert.equal(w.state.clock.now,22);assert.equal(w.state.outcome.waterService,true);assert.equal(w.state.paid.rest,3);assert.equal(JSON.stringify(await rain()),rainPreserved);
 await noOverflow('watch');await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/watch-short-success-390.png',fullPage:true});checks.push('Watch: full short-notice gate route succeeds through visible controls with three paid rest minutes, preserved as a counterexample; independent saves and 320/390/1280 layouts');
 await Promise.all(networkChecks);assert.deepEqual(errors,[]);assert.deepEqual(failedRequests,[]);
 const record={checkedAt:new Date().toISOString(),origin:base,browser:browser.version(),environment:'Isolated headless desktop Chrome. Viewport checks are not physical-device testing; late Rain checkpoints use valid public-API-generated fixtures.',checks,viewports:[320,390,1280],errors,failedRequests,prefetchRefusals};await writeFile(out+'/browser.json',JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify(record,null,2));
}finally{await context.close();await browser.close();}
