import {chromium} from '/Users/abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:375,height:667}});
const page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto('https://human.adamwhite.work/');
await page.locator('.collection-preview:not([hidden]) a.game').click();
await page.locator('#work-choices [data-job="gather-timber"]').click();
assert.equal(await page.locator('#clock').innerText(),'0');
await page.locator('#one-minute').click();
assert.equal(await page.locator('#clock').innerText(),'1');
const first=await page.locator('#player-job').innerText();
await page.reload();
await page.locator('#work-choices').waitFor();
assert.equal(await page.locator('#clock').innerText(),'1');
assert.equal(await page.locator('#player-job').innerText(),first);
await page.locator('#next-event').click();
const after=Number(await page.locator('#clock').innerText());assert.ok(after>1);
assert.deepEqual(errors,[]);
await writeFile('/tmp/hf-retirement-camp-smoke.json',JSON.stringify({url:page.url(),viewport:{width:375,height:667},firstJob:first,paidMinute:1,reloadPreserved:true,nextEventMinute:after,errors},null,2)+'\n');
await browser.close();
