import {createSignals,getSignalsView,exportSignals,restoreSignals,SIGNALS_TASKS} from '../src/games/signals.js';
import {createSession,pauseSession,toggleSession,commandSession,stopSession,stepSession,tickSession} from './signals-session.js';
const $=id=>document.getElementById(id),SAVE='human-last-light-v1',text=(id,value)=>{$(id).textContent=value;};
const sources={lookout:'Your lookout','landing-keeper':'Landing keeper','canal-lock':'At the canal lock'};
let session=createSession(),lastWall=performance.now(),saveFailed=false;
function notice(message){text('notice',message);$('notice').hidden=!message;}
function persist(){try{localStorage.setItem(SAVE,JSON.stringify(exportSignals(session.game)));saveFailed=false;text('save-status','Saved on this device. Reloads begin paused.');}catch{saveFailed=true;text('save-status','Device save unavailable. Download a save to keep this journey.');}}
function apply(update){const before=session.game;try{session=update(session);if(session.game!==before)persist();render();if(!before.outcome&&session.game.outcome){$('outcome').focus({preventScroll:true});$('outcome').scrollIntoView({block:'nearest',behavior:'smooth'});}}catch(error){session=pauseSession(session,'Paused. The action was not applied.');notice(error.message);render();}}
for(const [task,t] of Object.entries(SIGNALS_TASKS)){
 const b=document.createElement('button');b.type='button';b.id=`action-${task}`;b.className='choice';
 const head=document.createElement('span');head.className='choice-header';const title=document.createElement('span');title.className='choice-title';title.textContent=t.label;const cost=document.createElement('span');cost.className='choice-cost';cost.textContent=`${t.duration} min${task==='canal'?' · 1 fare':task==='radio'?' · 1 charge':task==='meal'?' · 1 meal':''}`;head.append(title,cost);
 const detail=document.createElement('span');detail.className='choice-detail';detail.textContent=t.detail;const note=document.createElement('span');note.id=`note-${task}`;note.className='choice-note';b.append(head,detail,note);
 $(['canal','ridge'].includes(task)?'routes':['radio','lookout'].includes(task)?'observations':'recovery').append(b);b.addEventListener('click',()=>{notice('');apply(s=>commandSession(s,task));});
}
function render(){
 const v=getSignalsView(session.game);text('minute',String(v.now).padStart(2,'0'));text('lens-status',v.outcome?v.outcome.delivered?'Lens delivered':'Too late':v.job&&['ridge','canal'].includes(v.job.task)?'Lens in transit':'Lens ready to carry');text('kit-status',v.outcome?.delivered?'Lens at the beacon':'One lens');
 for(const key of ['fares','charges'])text(key,String(v.resources[key]));text('meal-count',String(v.resources.meal));
 for(const key of ['fatigue','hunger']){$(key).value=v.person.body[key];text(`${key}-text`,`${Math.round(v.person.body[key]*100)}%`);}
 text('job',v.outcome?'Journey complete':v.job?SIGNALS_TASKS[v.job.task].label:'Ready to choose');text('job-time',v.job?`${v.job.endsAt-v.now} min left · finishes at minute ${v.job.endsAt}`:v.outcome?'Try another journey to make a different choice.':'Nothing moves until you advance time.');
 $('job-progress').max=v.job?v.job.endsAt-v.job.startedAt:1;$('job-progress').value=v.job?v.now-v.job.startedAt:0;$('stop').hidden=!v.job;
 text('time-status',session.reason);text('play',session.running?'Ⅱ Pause':'▶ Play');$('play').setAttribute('aria-pressed',String(session.running));
 for(const id of ['play','next-event','one-minute'])$(id).disabled=Boolean(v.outcome);text('next-event',v.job?'Next event →':v.inFlight.length?'Wait for reply →':v.now<v.launchDeadline?'Wait until minute 12 →':'Wait until closing →');
 for(const c of v.choices){$(`action-${c.task}`).disabled=!c.available;text(`note-${c.task}`,c.reason??(c.tooLate?`Finishes at ${c.finishesAt}; the beacon closes at 32.`:`Arrives at ${c.finishesAt}${['canal','ridge'].includes(c.task)?' if you leave now':''}.`));if(!['canal','ridge'].includes(c.task)&&!c.reason&&!c.tooLate)text(`note-${c.task}`,'');}
 const r=v.report;text('freshness',!r?'No observation':r.ageMinutes===0?'Observed now':`${r.ageMinutes} min old`);text('report-value',r?r.value:'Unseen');$('report-value').className=`report-value ${r?.value??''}`;
 text('report-provenance',r?`${sources[r.source]} · ${r.channel==='radio'?'radio reply':'direct observation'} · observed ${r.observedAt}, received ${r.deliveredAt}`:'Pay for a lookout or a radio request to learn about the landing.');
 text('report-age',r?r.ageMinutes===0?'You observed this at the current minute. The landing can still change while you travel.':`This describes minute ${r.observedAt}, not the current landing. A new lookout costs 3 minutes.`:'The current landing is not visible from here.');
 $('flights').hidden=!v.inFlight.length;text('flights',v.inFlight.map(f=>`Reply due at minute ${f.arrivesAt} (${f.arrivesAt-v.now} min away).`).join(' '));
 text('receipt-count',String(v.deliveries.length));$('receipts').replaceChildren();for(const d of [...v.deliveries].reverse()){const li=document.createElement('li'),title=document.createElement('strong'),detail=document.createElement('span');title.textContent=`${sources[d.source]}: ${d.value}`;detail.textContent=`Observed ${d.observedAt} · received ${d.deliveredAt} · ${d.ageMinutes} min old${d.olderThanNotebook?' · older than your notebook':''}`;li.append(title,detail);$('receipts').append(li);}
 $('outcome').hidden=!v.outcome;if(v.outcome){const o=v.outcome;text('outcome-title',o.delivered?o.launchSailed?'The beacon shines. The launch sails.':'The overnight beacon is restored.':'The beacon closed before you arrived.');text('outcome-detail',o.delivered?`You arrived by the ${o.route} at minute ${o.at}, with ${v.deadline-o.at} minutes to spare. ${o.launchSailed?'The evening crew could depart with the beacon lit.':'The evening launch missed its window and stayed in harbor.'}${o.failedCrossings?` ${o.failedCrossings} closed crossing${o.failedCrossings===1?'':'s'} cost time and fares along the way.`:''}`:'The lens remains undelivered. The full journey had to finish before minute 32; an action ending at closing was too late.');text('outcome-facts',`${o.faresRemaining} fares retained · ${o.chargesRemaining} radio charges retained · ${o.paidWorkMinutes} minutes of paid work`);$('outcome').classList.toggle('failure',!o.delivered);}
 $('journal').replaceChildren();for(const row of [...v.recent].reverse()){const li=document.createElement('li'),time=document.createElement('time'),body=document.createElement('span');time.textContent=`+${String(row.at).padStart(2,'0')}m`;body.textContent=row.message;li.append(time,body);$('journal').append(li);}
 text('researcher',`Game ${v.version}; Human/runtime ${v.humanVersion}/${v.runtimeVersion}; clock ${v.clockVersion}. One-minute canonical host cadence, no random draws. The actor view contains delivered observations only. Notebook selection uses newest observation time; report age does not estimate truth probability. Saves verify a bounded deterministic command replay. ${v.paid.lookout} paid lookout minutes; ${v.paid.canal+v.paid.ridge} paid carrying minutes.`);
 if(saveFailed)text('save-status','Device save unavailable. Download a save to keep this journey.');
}
$('stop').addEventListener('click',()=>apply(stopSession));$('one-minute').addEventListener('click',()=>apply(s=>stepSession(s,'minute')));$('next-event').addEventListener('click',()=>apply(s=>stepSession(s)));$('play').addEventListener('click',()=>{lastWall=performance.now();apply(toggleSession);});$('speed').addEventListener('change',()=>{lastWall=performance.now();apply(s=>pauseSession(s,'Speed changed. Press Play when ready.'));});
$('restart').addEventListener('click',()=>{notice('');apply(()=>createSession(createSignals({situation:$('situation').value})));$('new-episode').open=false;window.scrollTo({top:0,behavior:'smooth'});});
$('download').addEventListener('click',()=>{apply(s=>pauseSession(s,'Paused for download. The save will resume paused.'));try{const url=URL.createObjectURL(new Blob([JSON.stringify(exportSignals(session.game),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`last-light-minute-${session.game.clock.now}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(`Save could not be downloaded: ${e.message}`);}});
$('load').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;apply(s=>pauseSession(s,'Paused for import.'));try{if(file.size>65536)throw new Error('This file is too large for a journey save.');const game=restoreSignals(JSON.parse(await file.text()));notice('');apply(()=>createSession(game));}catch(e){notice(`Save was not loaded: ${e.message}`);}event.target.value='';});
function leave(){lastWall=performance.now();session=pauseSession(session,'Paused because you left this tab. Press Play when you return.');persist();render();}
window.addEventListener('pagehide',leave);document.addEventListener('visibilitychange',()=>{lastWall=performance.now();if(document.hidden)leave();});
setInterval(()=>{const now=performance.now(),elapsed=now-lastWall;lastWall=now;if(session.running&&!document.hidden)apply(s=>tickSession(s,elapsed,Number($('speed').value)));},250);
try{const raw=localStorage.getItem(SAVE);if(raw){if(raw.length>65536)throw new Error('Stored save too large.');session=createSession(restoreSignals(JSON.parse(raw)));}}catch(e){notice(`The stored journey could not be loaded (${e.message}). A fresh paused journey is ready.`);}render();
